Initial Implementation of Status Bar Details
JumpMind/openpos-framework pull request #1081
Opened 2021-01-20 21:51 UTC by kdelorey

# Summary
The Status bar can now be interacted with on **any** screen. A simple click will bring up a modal dialog. The intent is that the dialog will one day show details about status items and the server. Right now it does not do that but what it does do is provide a way to select a Printer and Payment device that shall be used. The status bar will display the currently selected printer/payment device too.

Note that this is just an initial implementation to support printer/payment selection. The status details still need to be implemented and currently lack full support for displaying on this dialog. There is also some styling considerations that need to be reviewed later too.

### Overlay Container
The CDK overlay container has been overridden as to not affect the entire screen but rather a selection portion of the screen.

### Status Move
The Status implementation was previously within the core folder but loaded through `SharedModule`. I have moved all of the status bar relevant items to the `shared` folder where it should live with its parent module.

### New `localize` Pipe
A new Angular pipe has been added that allows you too fulfill a i18n key from the client. It accepts a `base:key` format and uses a new `getString()` function on the `LocaleService` to invoke the `/i18n/value` endpoint on the server.

```html
<app-some-component [title]="'page:some.key.example' | localize">
  ....
```

This pipe will automatically respond to changes in locale too.

### Screenshots
![Example](https://user-images.githubusercontent.com/2295721/105244841-4e95de80-5b2e-11eb-9d61-e502b6a8865d.gif)

2021-01-20 21:57 UTC, kdelorey commented
I added pretty much everyone I could think of as a reviewer just so everyone could see some of these important changes. Its probably not required that everyone actually review it, but you may want to be familiar with the changes.

2021-01-20 23:50 UTC, blubaugha requested changes

2021-01-20 23:50 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
> +    static PERIPHERAL_DEVICE_SELECTION = "PeripheralDeviceSelection";
Sorry to nitpick 😄 , but the double-quotes should be replaced with single quotes

2021-01-20 23:50 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/peripheral-device-selection.ts
> +import { OpenposMessage } from "./message";
Replace these double-quotes with single quotes too

2021-01-20 23:50 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/locale.service.ts
>          this.sessionService.getMessages('LocaleChanged').subscribe(message => this.handleLocaleChanged(message));
If the server is set to a locale other than **en-US**, will this receive a `LocaleChanged` message on startup so the initial locale matches the server?

2021-01-20 23:55 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
> +    static PERIPHERAL_DEVICE_SELECTION = "PeripheralDeviceSelection";
Oh yeah good catch, I try to single quote in typescript but sometimes my hands get confused when switching between languages.

2021-01-20 23:59 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/locale.service.ts
>          this.sessionService.getMessages('LocaleChanged').subscribe(message => this.handleLocaleChanged(message));
It should. From what I observed a `'LocaleChanged '` event is observed on connect. This will work if the locale is changed on the fly too. I haven't change the behavior of this from what it was before.

2021-01-21 00:38 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/locale.service.ts
>          this.sessionService.getMessages('LocaleChanged').subscribe(message => this.handleLocaleChanged(message));
👍

2021-01-21 14:11 UTC, maxwellpettit approved these changes

2021-01-21 14:22 UTC, JJStarrett approved these changes

2021-01-21 15:04 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/peripheral-device-selection.ts
> +import { OpenposMessage } from "./message";
Fixed.

2021-01-21 15:04 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
> +    static PERIPHERAL_DEVICE_SELECTION = "PeripheralDeviceSelection";
Fixed.

2021-01-21 21:11 UTC, blubaugha approved these changes

2021-01-21 21:12 UTC, blubaugha commented
By the way, nice job on this!

2021-01-22 13:30 UTC, stevencarley approved these changes

2021-01-22 14:55 UTC, merged