Initial Release of Enhanced Training Mode Infrastructure
JumpMind/openpos-framework pull request #1094
Opened 2021-01-27 17:14 UTC by JoeBrownlee

### Issues Fixed
This feature addresses the following Petco JIRA items in whole or in part: #PDPOS-2759, #PDPOS-2823, #PDPOS-2824, #PDPOS-4117, #PDPOS-4241, #PDPOS-4243.

### Summary
This adds a greatly enhanced version of Training Mode to the OpenPOS Framework and Commerce. Users can train on most every function of the POS using real or "shadowed" data and services. This is highly configurable.

The basis of this change is a new concept of a **Device Mode**. The Device Mode for the POS is normally `default`. When the POS is in Training Mode, it is `training`. Other modes could be added in the future.

When in Training Mode, the POS can use **Shadow Tables** and **Shadow Endpoints**. Shadow tables are parallel versions of Commerce tables that are separate from the main production database tables. They have the same name and structure as the "normal" tables, except that they are prefixed with a special shadow prefix, `TNG` by default. The prefix is configurable. The shadow tables are used while the POS is in Training Mode.

Likewise, shadow endpoints can be created to "override" normal POS behavior while in Training Mode. A shadow endpoint will have the same service path as the default endpoint, but its implementation will be `training`.

The `application.yml` file in the commerce-server project controls the configuration of shadow tables. Its `deviceMode` tag must match the Training Mode value `training`. It specifies the shadow table prefix, whether series should bee validated at startup, and tables to be included or excluded from shadowing. `*` can be used as a wildcard in table names. For example:
```
shadowTables:
    deviceMode: training
    tablePrefix: tng
    validateQueries: true
    includes:
      - sls_*
      - cust_*
      - ops_*
    excludes:
      - sls_rtn_policy
      - sls_tender
      - cust_phone_blacklist
  ```

For the POS to adjust SQL to use the shadow tables, the `*-query.yml` files need to have their SQL written to use the model class name for a given entity rather than a hard-coded table name. For example, a query like `select * from SLS_TRANS` would be written instead as `select * from TransModel`. As part of this work, all existing SQL in the query files has been changed to conform to this. Note _one important exception_: if a query has a join or sub select that uses a table outside its own module, those table names must be left as the actual table name rather than the model class name. For example, in `sls-query.yml`, there is SQL that selects data from the `USR_USER` table. That reference must stay as the actual table name.

The GUI has been changed as well. In previous versions of Commerce, clicking the **Training Mode** button on the Home screen would allow the operator to perform one transaction and then they would exit Training Mode. Now, when the operator clicks the **Training Mode** button, the POS will be in Training Mode until the operator explicitly exits by returning to the Home screen and clicking the **Training Mode** button again. Entering Training Mode requires a manager's authorization. While in Training Mode, the color scheme changes to a grey palette and a watermark appears at the top of each screen to indicate the POS is in Training Mode.

This is the initial version of this feature. Future PRs will add additional functionality.

### Database Changes
There are no database changes per se, other than the fact that shadow tables will be created automatically at startup as specified in the `application.yml` file. Existing tables are not changed.

### Screenshots
<img width="1365" alt="Screen Shot 2021-01-27 at 12 06 55 PM" src="https://user-images.githubusercontent.com/24355694/106027169-a1c0e180-6098-11eb-9144-67e9fb0df552.png">
<img width="1371" alt="Screen Shot 2021-01-27 at 12 06 33 PM" src="https://user-images.githubusercontent.com/24355694/106027204-ab4a4980-6098-11eb-9916-ec9c697da962.png">
<img width="1367" alt="Screen Shot 2021-01-27 at 12 07 43 PM" src="https://user-images.githubusercontent.com/24355694/106027236-b43b1b00-6098-11eb-87e4-07de0c4268fd.png">

2021-01-27 23:42 UTC, jrmihalick requested changes
Some of my comments are just questions, others are minor changes.  This is a ton of work.  Overall a really nice PR.

2021-01-27 23:42 UTC, jrmihalick commented on openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
> +    private String deviceMode = DEVICE_MODE_DEFAULT;
I'm wondering if we should make this a TypeCode.  If the type of this were DeviceModeTypeCode instead of String, would that make life harder?

2021-01-27 23:42 UTC, jrmihalick commented on openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
> +    private String deviceMode = DEVICE_MODE_DEFAULT;
Might cause issues with your changes in StateManagerContainer.

2021-01-27 23:42 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +                    templates.addQueries("training", queryTemplates.getQueries());
Would be nice if this could use the same constant values in DeviceModel, but DeviceModel is in another module.

2021-01-27 23:42 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +            // column.setPrimaryKeySequence(table.getPrimaryKeyColumnCount() + 1);
Should this if stmt be removed?

2021-01-27 23:42 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
> +                // dbCol.setPrimaryKeySequence(new ArrayList<>(metaData.getPrimaryKeyFieldNames()).indexOf(dbCol.getName()));
Remove?

2021-01-27 23:42 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
> +            // fieldMetaData.getColumn().setPrimaryKeySequence(primaryKeySequence++);
Remove?

2021-01-27 23:42 UTC, jrmihalick commented on openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
> +    //  Per CEH, the below is needed for AEO only.
??

2021-01-27 23:42 UTC, jrmihalick commented on openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/TestPersistCarsConfig.java
> +            AugmenterConfigs augmenterConfigs = new AugmenterConfigs();
Are there any unit tests which test a simple shadow table configuration?

2021-01-27 23:51 UTC, JoeBrownlee commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +            // column.setPrimaryKeySequence(table.getPrimaryKeyColumnCount() + 1);
This came over from Commerce master but we don't have the most recent version Column on 1.9. So we can get rid of it for now, but it will come back.

2021-01-28 01:58 UTC, JoeBrownlee commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
> +                // dbCol.setPrimaryKeySequence(new ArrayList<>(metaData.getPrimaryKeyFieldNames()).indexOf(dbCol.getName()));
This came over from Commerce master but we don't have the most recent version Column on 1.9. So we can get rid of it for now, but it will come back.

2021-01-28 01:58 UTC, JoeBrownlee commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
> +            // fieldMetaData.getColumn().setPrimaryKeySequence(primaryKeySequence++);
This came over from Commerce master but we don't have the most recent version Column on 1.9. So we can get rid of it for now, but it will come back.

2021-01-28 02:04 UTC, JoeBrownlee commented on openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
> +    //  Per CEH, the below is needed for AEO only.
Chris said the autowire is not needed other than in AEO. Commerce/Petco definitely don't run with that line in place. Don't ask me to explain that. I just know it doesn't work with that enabled.

2021-01-28 02:11 UTC, JoeBrownlee commented on openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/TestPersistCarsConfig.java
> +            AugmenterConfigs augmenterConfigs = new AugmenterConfigs();
As of this moment, there are no tests, but I haven't gotten to the Cucumber task yet.

2021-01-28 02:14 UTC, JoeBrownlee commented on openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
> +    private String deviceMode = DEVICE_MODE_DEFAULT;
In general, I'd like to see that constant be in a place that has more visibility. Too many places can't see it in DeviceModel, therefore you end up hard-coding it which defeats the purpose. Not sure the right place, but I could look into that -- unless someone wants to give me the right answer!

2021-01-28 02:15 UTC, JoeBrownlee commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +                    templates.addQueries("training", queryTemplates.getQueries());
Exactly, I agree. Open to suggestions...

2021-01-28 13:06 UTC, jrmihalick commented on openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
> +    private String deviceMode = DEVICE_MODE_DEFAULT;
After looking at the rest of your PR, probably shouldn't mess with this.  You can ignore my comment here

2021-01-28 13:08 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +                    templates.addQueries("training", queryTemplates.getQueries());
Disregard as per my other comment above

2021-01-28 13:08 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +            // column.setPrimaryKeySequence(table.getPrimaryKeyColumnCount() + 1);
Ok, I see, don't worry about it

2021-01-28 13:09 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
> +                // dbCol.setPrimaryKeySequence(new ArrayList<>(metaData.getPrimaryKeyFieldNames()).indexOf(dbCol.getName()));
Same as other, don't worry about it

2021-01-28 13:09 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
> +            // fieldMetaData.getColumn().setPrimaryKeySequence(primaryKeySequence++);
Same

2021-01-28 13:15 UTC, jrmihalick commented on openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/TestPersistCarsConfig.java
> +            AugmenterConfigs augmenterConfigs = new AugmenterConfigs();
ok, once we get this PR put to bed, let's try to get a unit test or two put in before Cucumber tests.  We might have to drop kick cucumber tests until next release.

2021-01-29 12:54 UTC, jrmihalick approved these changes

2021-02-02 16:31 UTC, merged