Make displaying peripheral selection in status bar configurable
JumpMind/openpos-framework pull request #1116
Opened 2021-02-09 22:22 UTC by levshunovm

### Summary
Make displaying peripheral selection in status bar configurable.

2021-02-11 15:04 UTC, kdelorey commented
@chenson42 did we actually want this configurable? I assumed this would lead into the status details page always, but I guess too be fair, that's not done yet and I suspect its not on the radar.

2021-02-11 15:13 UTC, kdelorey commented
The impetus for this PR is actually all caused by a bug in the backed server. The only thing this configuration should do is prevent the status details dialog from appearing.

The backend server shouldn't be sending peripheral messages to the client when not in mobile mode. This will give the possibility in the future to have selectable peripherals for non-mobile devices in the future; but I realize that this not a goal, I just think it is something we can easily have just in case.

Reach out to me and I can point you to what needs to happen in the backend.

2021-02-11 15:59 UTC, kdelorey requested changes

2021-02-11 15:59 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.ts
> +    if (this.selectable) {
You have whether or not the status details dialog is shown based on if peripheral selection exists. This should probably not be the case since the status details is intended to be something greater than just peripheral selection. You may want a separate configuration that lives with the status stuff for now.

Also "selectable" can be entirely inferred. If you don't receive any messages then you can assume `false`. You can assume `|= true` when you receive a message with a selectable array size > 0.

2021-02-11 16:53 UTC, levshunovm commented
@kdelorey I tried to just disable these messages in the backend, but it leads to the problems with combineLatest on lines 42-77 in status-bar.component.ts. It isn't working when one of the arguments is empty, so it disables the whole line in the status including store and device number. I tried a lot of different things, but still can't find a way to make it works. So, could you please advice how to fix it?

2021-02-11 17:03 UTC, kdelorey commented
> @kdelorey I tried to just disable these messages in the backend, but it leads to the problems with combineLatest on lines 42-77 in status-bar.component.ts. It isn't working when one of the arguments is empty, so it disables the whole line in the status including store and device number. I tried a lot of different things, but still can't find a way to make it works. So, could you please advice how to fix it?

Something like this should do it. This is off the top of my head, so you may need to massage it a little, but `publishBehavior()` will always make sure there's a value there when its first subscribed to.
```ts
peripheralSelectionService.peripheralCategories$.pipe(
    switchMap(categories => combineLatest( ... )),
    publishBehavior(new Array<CategoryWithName>()),
    refCount()
)
```

2021-02-11 21:04 UTC, levshunovm commented
> > @kdelorey I tried to just disable these messages in the backend, but it leads to the problems with combineLatest on lines 42-77 in status-bar.component.ts. It isn't working when one of the arguments is empty, so it disables the whole line in the status including store and device number. I tried a lot of different things, but still can't find a way to make it works. So, could you please advice how to fix it?
> 
> Something like this should do it. This is off the top of my head, so you may need to massage it a little, but `publishBehavior()` will always make sure there's a value there when its first subscribed to.
> 
> ```ts
> peripheralSelectionService.peripheralCategories$.pipe(
>     switchMap(categories => combineLatest( ... )),
>     publishBehavior(new Array<CategoryWithName>()),
>     refCount()
> )
> ```

Thanks! It works. I also tried to fix all your other comments in both repos. Could you please re-review?

2021-02-11 22:01 UTC, kdelorey requested changes
There's a pretty big issue with mixing asynchronous code with synchronous code that needs to be looked at again. Other than that I think everything seems good.

2021-02-12 13:46 UTC, levshunovm commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.service.ts
> +  }
It seems that when `peripheralCategories$` is empty, the pipe's body is ignored and function just returns observable with false, which is totally fine in our case, but I had to invert the function and rename it. 
Also, I haven't found a way to work with `Observable<boolean>` without `subscribe`, so not sure if I fixed an issue with mixing asynchronous code with synchronous code that you've mentioned above.

2021-02-12 14:27 UTC, kdelorey requested changes

2021-02-12 14:27 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status.service.ts
> +        }
So you moved the mixing async with sync code problem here. You'll need to update this whole function to understand that you're doing async stuff here.

Something like this should take care of it; might not be perfect though.

```ts
public openDetails() {
    if (this.detailsDialog) {
        return;
    }

    this.statusDetailsService.isDetailsNotEmpty().pipe(
        take(1),
        filter(isDetailsNotEmpty => !isDetailsNotEmpty),
        map(() => {
            this.detailsDialog = this.dialog.open(StatusDetailsComponent, { minWidth: '75%' })
            return this.detailsDialog;
        }),
        mergeMap(dialog => dialog.afterClosed())
    ).subscribe({
        // don't need to worry about the subscription because the
        // observable will be automatically completed by the
        // source
        complete: () => {
            this.detailsDialog = undefined;
        }
    })
}
```

2021-02-12 14:29 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.service.ts
> +  }
Ah, if you didn't want to change the name you could have just flipped the `boolean` expression to `v.length <= 0`. That was my bad. But regardless this should be stable now.

2021-02-12 15:48 UTC, levshunovm commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status.service.ts
> +        }
Thanks a lot for your help! I think it should be good now.

2021-02-12 15:58 UTC, kdelorey approved these changes

2021-02-12 16:14 UTC, merged