Round up donation at tendering
JumpMind/openpos-framework pull request #1139
Opened 2021-02-18 19:37 UTC by JJStarrett

### Issues Fixed
 - [4220](https://petcoalm.atlassian.net/browse/PDPOS-4220)

### Summary
Adds UI support for an optional "Round Up" donation button to the tender options screen. Most of the buttons functionality (aside from the checkmark icon) is driven from the server, so in the future the button's functionality could easily be altered on the server without editing the client.

### Screenshots
https://user-images.githubusercontent.com/39058176/108403310-90c54500-71ec-11eb-9753-951824c1879a.mp4

2021-02-18 21:38 UTC, blubaugha reviewed
This looks nice @JJStarrett , just a couple comments:

1. I think you should move the icon to the left of the text because that's where other icons are placed in the app
2. I'm curious why this round-up donation button was added here. Mainly because there's an option to round up on the **Charity Donation Dialog** right before tendering:
<img width="1792" alt="Screen Shot 2021-02-18 at 4 35 10 PM" src="https://user-images.githubusercontent.com/3991426/108424826-ab58e780-7207-11eb-8b86-07dc5962a11f.png">

2021-02-18 21:58 UTC, JJStarrett commented
> 1. I think you should move the icon to the left of the text because that's where other icons are placed in the app

Good point, adjusted: 
![image](https://user-images.githubusercontent.com/39058176/108426859-4bb00b80-720a-11eb-8743-7d2e4a0711ce.png)

> 2. I'm curious why this round-up donation button was added here. Mainly because there's an option to round up on the **Charity Donation Dialog** right before tendering:

This issue has been in my queue for quite a long time now, and I think this was the reason why. I think Petco specifically requested this - JDA has functionality similar to this where the round up option is separated and stackable with other donations. And, I think that's the primary reason.

2021-02-18 22:22 UTC, JJStarrett commented
> > 1. I think you should move the icon to the left of the text because that's where other icons are placed in the app
> 
> Good point, adjusted:

So after thinking about this a little more, I'm wondering if it does actually make sense to put it on the right. Most Option Items in the app have their icons on the **left** - which move you forward in a flow - while items that "do something" to the current screen actually trend towards having their icons on the **right**, like "remove" and "options" on the sale screen:

![image](https://user-images.githubusercontent.com/39058176/108429236-b4e54e00-720d-11eb-8b7c-2f89bf3a0ded.png)
![image](https://user-images.githubusercontent.com/39058176/108429262-bd3d8900-720d-11eb-8cf2-9ee0afe82e89.png)

Perhaps it would make sense to put Round Up's icon on the **right** since it doesn't move the user through tendering, it just alters the current state. Though, it would be the only button in tendering with its icon on the right then. @mmichalek I'd be curious for your thoughts on this

2021-02-18 22:30 UTC, stojankz reviewed
my only comment is that I think the icon for this button should match the icon of the Round Up button from the donations screen. Either change this one to the + or the one on the Donation screen to this one for consistency

2021-02-19 12:08 UTC, jrmihalick commented
> my only comment is that I think the icon for this button should match the icon of the Round Up button from the donations screen. Either change this one to the + or the one on the Donation screen to this one for consistency

I agree with @stojankz .  I think use the '+' icon since it's more indicative of the button function.

@blubaugha Petco specifically asked for this feature because some customer want to both round up AND donate a fixed amount through the PIN Pad or when the cashier asks them.

2021-02-19 12:14 UTC, jrmihalick requested changes

2021-02-19 12:14 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.ts
> +        if (this.screenData.roundUpAvailable)
this.isRoundUpAvailable = this.screenData.roundUpAvailable

2021-02-19 15:03 UTC, JJStarrett commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.ts
> +        if (this.screenData.roundUpAvailable)
Adjusted.

2021-02-19 15:04 UTC, JJStarrett commented
New button:

![image](https://user-images.githubusercontent.com/39058176/108521528-cffd9f80-7299-11eb-83df-e0b1244650c2.png)

2021-02-19 15:27 UTC, mmichalek commented
How about this one?
![image](https://user-images.githubusercontent.com/4398634/108524375-f5d87380-729c-11eb-98bd-0e45600ddcf5.png)

It's from https://materialdesignicons.com/ - called heart-plus-outline

2021-02-19 15:54 UTC, JJStarrett commented
> How about this one?
> ![image](https://user-images.githubusercontent.com/4398634/108524375-f5d87380-729c-11eb-98bd-0e45600ddcf5.png)
> 
> It's from https://materialdesignicons.com/ - called heart-plus-outline

Oh, I like this one. I think it communicates rounding up is a charity donation as well as increasing your current balance. It looks like our icon.service.ts can't find the heart_plus_outline.svg. Is there a way to add new icons to the project?

2021-02-19 16:18 UTC, JJStarrett commented
![image](https://user-images.githubusercontent.com/39058176/108530996-2ff94380-72a4-11eb-9803-b931983b628e.png)

I would change the round up button on the prompt to this icon as well if we made this change. Thoughts?

2021-02-19 16:26 UTC, jrmihalick commented
> I would change the round up button on the prompt to this icon as well if we made this change. Thoughts?

I agree.

2021-02-19 16:59 UTC, jrmihalick approved these changes

2021-02-19 17:15 UTC, stojankz approved these changes

2021-02-19 18:35 UTC, merged