Feature/record sql statement values in data access violation error
JumpMind/openpos-framework pull request #1151
Opened 2021-02-24 16:59 UTC by JJStarrett

### Issues Fixed
 - Logging to help diagnose [5009](https://petcoalm.atlassian.net/browse/PDPOS-5009)

### Summary
Adds logging for data violations exceptions when performing insert, update, or delete statements and records the values trying to be altered. Also adds a small bit of warning logging to note when tag values are inserted with an empty value instead of the default '*' or some other non-empty value. Both are set at the **warning** level as they should not often happen.

### Screenshots
![image](https://user-images.githubusercontent.com/39058176/109034600-cf984680-7695-11eb-8c71-1a5fdabc8719.png)

2021-02-24 17:11 UTC, jrmihalick approved these changes

2021-02-24 17:25 UTC, mmichalek requested changes

2021-02-24 17:25 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        log.warn(errorStatement.toString());
This should be the message of a re-thrown exception.   Like:
throw new PersistException("SQL Statement caused exception: " + statement, ex);

I think it's important to keep logging consolidated to one entry per error as much as possible. Otherwise, in a highly concurrent environment, you can end up with a single error quite spread out in the log.

2021-02-24 17:25 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        for (Object value : values) {
We should use LogSqlBuilder.buildDynamicSqlForLog(...) for format the SQL statment for the log.

2021-02-24 18:27 UTC, JJStarrett commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        log.warn(errorStatement.toString());
I was actually initially re-throwing a PersistException here, but I noticed some insert statements that would normally fail over to an update, would not, and the app would break where it probably shouldn't. I could re-throw the DataAccessViolation Exception and catch it where the save() method in DBSession.java catches DuplicateKey Exceptions:

```
                try {
                    insert(model, table);
                } catch (DuplicateKeyException ex) {
                    log.info("Insert of entity failed, failing over to an update: " + argModel);
                    int updateCount = update(model, table);
                    if (updateCount < 1) {
                        throw new PersistException("Failed to perform an insert or update on entity. Do the DB primary key and unique fields "
                                + "match what's understood by the code?  " + argModel, ex);
                    }
                }
```

Or is there a different exception I might be able to throw that would not halt the application?

2021-02-24 18:35 UTC, JJStarrett commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        for (Object value : values) {
Adjusted. Thanks for the heads-up, Mark

2021-02-24 18:46 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        log.warn(errorStatement.toString());
Ah - it should just check and re-throw the DuplicateKeyException actually.

2021-02-24 19:50 UTC, JJStarrett commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        log.warn(errorStatement.toString());
Gotcha, adjusted.

2021-02-24 20:32 UTC, merged

2021-02-25 00:46 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        throw new DuplicateKeyException(errorStatement.toString(), e);
Maybe I'm missing something - but this method says it will "log" (logDMLError) but actually throws an exception . I'm also not seeing how we know to throw a DuplicateKeyException the way this is currently.  Let's chat about it tomorrow @JJStarrett