Added config to allow manual entry of receipt detail. Disabled by default.
JumpMind/openpos-framework pull request #1176
Opened 2021-03-09 12:10 UTC by apomanytskyi

Added logic and config to allow manual entry of receipt detail. Disabled by default.
To enable - set openpos.returns.allowManualEntryOfReceiptDetails=true
![allowRecreateTrans](https://user-images.githubusercontent.com/77682108/110468492-0718e100-80e1-11eb-9bf0-eb5787338314.gif)

2021-03-10 20:04 UTC, stevencarley submitted a review, later dismissed

2021-03-10 20:04 UTC, stevencarley commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/return/return-trans-details/return-trans-details-dialog.component.scss
> +::ng-deep {
change to :host ::ng-deep to prevent style from possibly leaking to other components.

2021-03-11 12:15 UTC, dankaste requested changes

2021-03-11 12:15 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/return/add-item-to-return-transaction/add-item-to-return-transaction-dialog.component.html
> +<app-dialog-header></app-dialog-header>
Did just using the existing dynamic for screen not work here?

2021-03-11 12:15 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/return/return-trans-details/return-trans-details-dialog.component.html
> +                          [disabled]="employeeTransaction.readOnly" [labelPosition]="employeeTransaction.labelPosition"
I don't think we need disabled here. In the case where its not used we just won't add it to the screen. Also don't send over the labelPosition. The server shouldn't really care about layout decisions

2021-03-16 12:05 UTC, dankaste approved these changes

2021-03-16 12:05 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/return/return-trans-details/return-trans-details-dialog.component.html
> +                          [disabled]="employeeTransaction.readOnly" labelPosition="'before'"
Does labelPosition="'before'" work? I think if you take the [] off labelPosition you don't need the single ticks '' anymore

2021-03-16 12:35 UTC, apomanytskyi commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/return/return-trans-details/return-trans-details-dialog.component.html
> +                          [disabled]="employeeTransaction.readOnly" labelPosition="'before'"
Yes, you are right, thanks!

2021-03-16 14:13 UTC, dankaste approved these changes

2021-03-17 09:33 UTC, merged