Loyalty Member Name and Member ID get cut off
JumpMind/openpos-framework pull request #1183
Opened 2021-03-11 13:41 UTC by apomanytskyi

JMC Mobile - Loyalty Member Name and Member ID get cut off
We always had font size 24px. In browser we can see that the text does not fit.
On a mobile device, the surname is just truncated.
![1938_problem](https://user-images.githubusercontent.com/77682108/110795566-a8d63480-827f-11eb-805d-a55e21cbf24b.gif)
Suggestion - use dynamic font size for loyalty button.
![1938_fixed](https://user-images.githubusercontent.com/77682108/110795789-e8048580-827f-11eb-89ec-84ba71ed7ced.gif)

2021-03-11 14:01 UTC, dankaste approved these changes

2021-03-11 14:01 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                        font-size: 1.5vw;
would be better to do this with our responsive classes and font sizes. You should be able to see evidence of this elsewhere in the codebase. look for usage of the response-class directive

2021-03-11 14:02 UTC, dankaste requested changes
use responsive font sizes instead of vw

2021-03-12 11:55 UTC, apomanytskyi commented
@dankaste
Yes, but with the responsive-class there still will be a bug in some cases ... It all depends on how long the first name + last name will be ...
Because this is the dynamics length data - the only solution I can see - a fully dynamic text size calculation.
The default size is now 24px. If use %text-md, the bug remains.
If change it to %text-sm - the bug will be fixed, but no one asked to make the text smaller by default.
If you have any other suggestions, it will be cool... because now I'm not sure this is the best possible solution...
![1928_fix_with_responsive](https://user-images.githubusercontent.com/77682108/110936829-278fa800-833a-11eb-96a2-e8da9338e065.gif)

2021-03-12 13:46 UTC, dankaste commented
@apomanytskyi what if we just allow wrapping in the super long case and I'd just make it smaller I don't think it needs to be 24px

2021-03-15 08:35 UTC, apomanytskyi commented
Ok, how about this: I reduced the default font-size to 18px. Now the bug will be fixed, because first and last name from test-case will fit.
For super long cases - the text will be hidden outside the borders of the button, but will be available on scrolling.
I do not think that this one will be used often and will appear, but I would like to leave the ability to fully view the first name and last name, regardless of its length.
Perhaps I can try to split the text into multiple lines if needed, but I'm afraid the other styles might break.
Or I can just cut the text by "text-overflow" but I like this solution less ...

![1928_with_scroll](https://user-images.githubusercontent.com/77682108/111125168-fe5d5a80-8579-11eb-9b48-4d9363446d8c.gif)

2021-03-15 14:24 UTC, dankaste commented
> Ok, how about this: I reduced the default font-size to 18px. Now the bug will be fixed, because first and last name from test-case will fit.
> For super long cases - the text will be hidden outside the borders of the button, but will be available on scrolling.
> I do not think that this one will be used often and will appear, but I would like to leave the ability to fully view the first name and last name, regardless of its length.
> Perhaps I can try to split the text into multiple lines if needed, but I'm afraid the other styles might break.
> Or I can just cut the text by "text-overflow" but I like this solution less ...
> 
> ![1928_with_scroll](https://user-images.githubusercontent.com/77682108/111125168-fe5d5a80-8579-11eb-9b48-4d9363446d8c.gif)

I think I'd rather wrap than scroll. It really shouldn't ever be the case that its that long anyways. this is just incase.

2021-03-15 20:54 UTC, apomanytskyi commented
text wrapping
![1928_text_wrap](https://user-images.githubusercontent.com/77682108/111219976-46fc2e80-85e1-11eb-9fee-d8ea8ee5a460.gif)

2021-03-16 10:47 UTC, dankaste approved these changes

2021-03-16 10:52 UTC, merged