Feature/membership
JumpMind/openpos-framework pull request #1190
Opened 2021-03-17 14:41 UTC by r-cochran

### Summary
Clicking the customer loyalty button when a customer is linked will now show the customer details dialog that shows details, membership status, available loyalty rewards/promotions, and past loyalty rewards/promotions. Added the membership status display to the customer loyalty button when a customer is linked.

### Screenshots
![image](https://user-images.githubusercontent.com/2406987/111484158-def63700-870b-11eb-9d4f-3f505ad752d9.png)
![image](https://user-images.githubusercontent.com/2406987/111484708-60e66000-870c-11eb-8c87-271e3d2c7144.png)
![image](https://user-images.githubusercontent.com/2406987/111484804-752a5d00-870c-11eb-9ff8-afce57afae73.png)
![image](https://user-images.githubusercontent.com/2406987/111485594-20d3ad00-870d-11eb-8a2e-4b00a986bd78.png)
![image](https://user-images.githubusercontent.com/2406987/111485648-2d580580-870d-11eb-8589-400b0cae288d.png)
![image](https://user-images.githubusercontent.com/2406987/111485697-39dc5e00-870d-11eb-99ca-605768d64f4c.png)

2021-03-17 20:19 UTC, blubaugha reviewed
Nice job!

2021-03-18 10:48 UTC, dankaste requested changes

2021-03-18 10:48 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.html
> +    <app-icon [iconName]="'mail_outline'" [iconClass]="'material-icons mat-18'"></app-icon>{{customer.email}}
we probably shouldn't hardcode the icon names on the client. Typically we try and drive these from the server

2021-03-18 10:48 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/_membership-display-theme.scss
> +    mat-chip.not-in {
I'd recommend wrapping these chip styles with you component selector app-membership-display. Since the theme are globally applied this will actually apply to ALL mat-chips that have the .not-in or .in classes, which is probably nothing but who knows what someone is going to do in the future. And with the !important usage I could see someone chasing their tails. just better to encapsulate it now.

2021-03-18 10:48 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/_rewards-history-line-item-theme.scss
> +    .status {
Same here. You'll want to encapsulate this with your component selector otherwise this sets anything in the whole app with a .status class.

2021-03-18 10:48 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.scss
> +        font-size: $text-xs-mobile*1.75;
I noticed you apply these scalers to the font size variables in several places. I'm not sure the tablet should really be referencing the mobile font size.

2021-03-18 10:48 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.ts
> +import {MediaBreakpoints, OpenposMediaService} from "../../../core/media/openpos-media.service";
I realize it's just a style thing, but I believe our linter is setup for single quotes over double quotes.

2021-03-18 22:53 UTC, r-cochran commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.html
> +    <app-icon [iconName]="'mail_outline'" [iconClass]="'material-icons mat-18'"></app-icon>{{customer.email}}
I believe these should resolved now if you want to check again

2021-03-18 22:53 UTC, r-cochran commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/_membership-display-theme.scss
> +    mat-chip.not-in {
added a class to the list wrapper and then encapsulated this css in that

2021-03-18 22:54 UTC, r-cochran commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.scss
> +        font-size: $text-xs-mobile*1.75;
I had originally borrowed the styles from the primary button styling. I have now converted the tablet sizes to $text-sm

2021-03-19 13:33 UTC, blubaugha approved these changes

2021-03-19 17:31 UTC, dankaste approved these changes

2021-03-19 17:40 UTC, merged