Add privacy restriction functionality to customer-search-results.
JumpMind/openpos-framework pull request #1220
Opened 2021-03-30 16:51 UTC by TyShingler

### Summary
When a customer is flagged as having Privacy Restrictions search results will no longer display any information, other than the name of the customer and a messages of "Privacy Restricted" as well as being  not selectable. No customer information other than name is passed to the font-end either.

### Screenshots
Single customer

HP Engage
![image](https://user-images.githubusercontent.com/16402926/113025590-1de9ab00-9156-11eb-9b54-f3f8f97b385d.png)

ELO POS
![image](https://user-images.githubusercontent.com/16402926/113025618-25a94f80-9156-11eb-9afd-dbeeb5b01647.png)

IPad
![image](https://user-images.githubusercontent.com/16402926/113025641-2c37c700-9156-11eb-91fe-d7b4f7ede53e.png)

Multiple customers

HP Engage
![image](https://user-images.githubusercontent.com/16402926/113025888-71f48f80-9156-11eb-9c03-24c66d335d67.png)

ELO POS
![image](https://user-images.githubusercontent.com/16402926/113025921-7caf2480-9156-11eb-882d-830c201606c0.png)

IPad
![image](https://user-images.githubusercontent.com/16402926/113026044-a1a39780-9156-11eb-89e7-9cee72b93c91.png)

2021-03-30 18:07 UTC, blubaugha requested changes

2021-03-30 18:07 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-search-result-dialog/customer-search-result-dialog.interface.ts
> +    privacyRestricted: string
Should the `privacyRestricted` property type be a `boolean` instead of a `string`?

2021-03-30 18:07 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/display-customer-lookup/display-customer-lookup.component.spec.ts
> +            });
Sorry for nitpicking 😏 but the double quotes here should be single quotes

2021-03-30 18:07 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-search-result-dialog/customer-search-result-dialog.interface.ts
> +    privacyRestricted: string
Oh never mind - I see how it's used. How about changing the name to something like, `privaceRestrictedMessage` so the usage is a little clearer?

2021-03-30 18:07 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/display-customer-lookup/display-customer-lookup.component.spec.ts
> +            });
Same here - change double quotes to single quotes

2021-03-31 15:34 UTC, TyShingler commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/display-customer-lookup/display-customer-lookup.component.spec.ts
> +            });
Its np, I just got get into the habit.

2021-03-31 16:23 UTC, blubaugha approved these changes

2021-03-31 16:31 UTC, merged