Feature/issue 3512
JumpMind/openpos-framework pull request #1279
Opened 2021-04-19 15:38 UTC by TyShingler

### Issues Fixed
Commerce #3512

### Summary
Change sampling strategy to **instead** of using `@Sample` annotations, use database entries in `CTX_CONFIG` and yaml configurations. 

Currently the feature "Confirm you can add a config via database on a new endpoint" will not work!

2021-04-19 18:09 UTC, jrmihalick commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
> +        Optional<ServiceSampleModel> serviceSampleModel = Optional.empty();
I'm thinking we should keep a simple hashmap cache of the endpoint paths which have sampling enabled so we don't have to do this filtering constantly, do you agree @chenson42 and @mmichalek ?

2021-04-19 18:52 UTC, mmichalek commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
> +        Optional<ServiceSampleModel> serviceSampleModel = Optional.empty();
Sure, caching would be great.

2021-04-19 19:03 UTC, jrmihalick requested changes
See comment above

2021-04-20 13:25 UTC, TyShingler commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
> +        Optional<ServiceSampleModel> serviceSampleModel = Optional.empty();
@jrmihalick We talked about the cacheing, would you prefer using a hashmap over say the spring annotation, cacheable? It is used for cashing in ServiceConfig.java on getServiceConfig().

2021-04-20 14:15 UTC, jrmihalick commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
> +        Optional<ServiceSampleModel> serviceSampleModel = Optional.empty();
You can use spring @Cacheable if you want.  Just can't be in the EndpointInvoker class due to spring proxying.

2021-04-20 14:28 UTC, TyShingler commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
> +        Optional<ServiceSampleModel> serviceSampleModel = Optional.empty();
Using cacheable seems like I would have to add unnecessary complexity then. Will use the hashmap solution.

2021-04-20 17:31 UTC, jrmihalick approved these changes

2021-04-21 18:48 UTC, jrmihalick approved these changes

2021-04-22 12:41 UTC, merged