Feature/zero conf 1 9
JumpMind/openpos-framework pull request #1315
Opened 2021-05-04 15:34 UTC by eddielegg-le

### Summary
Add support for auto personalization of devices (beginning with those running Capcacitor applications).

Implements ZeroConf on both server side and client side for service discovery, then adds DevicePersonalizationModel to store records of device personalization settings by device name.

If ZeroConf configuration fails, will fall back to manual personalization

### Database Changes
Add `dev_device_personalization` table with fields:
- `device_name` pk    
- `server_address`
- `server_port`
- `device_id`
- `app_id`
- `personalization_params`

2021-05-04 17:14 UTC, dankaste reviewed
Shouldn't there be a server endpoint?

2021-05-04 17:20 UTC, eddielegg-le commented
> Shouldn't there be a server endpoint?

Yup, that'll be in the commerce PR

2021-05-04 17:30 UTC, dankaste commented
> > Shouldn't there be a server endpoint?
> 
> Yup, that'll be in the commerce PR

any reason it can't be in openpos? I think the other device personalization stuff is there. (I am probably the one that put it in commerce for the POC and that probably wasn't the right place)

2021-05-04 18:04 UTC, eddielegg-le commented
> > > Shouldn't there be a server endpoint?
> > 
> > 
> > Yup, that'll be in the commerce PR
> 
> any reason it can't be in openpos? I think the other device personalization stuff is there. (I am probably the one that put it in commerce for the POC and that probably wasn't the right place)

Moved base implementation to openpos

2021-05-04 18:40 UTC, jrmihalick requested changes

2021-05-04 18:40 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return Capacitor.isNative;
Maybe you are already working this out, but should this maybe be behind another Service interface?  Feels strange to have a reference to Capacitor in here.

2021-05-04 18:40 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.http.get<DevicePersonalizationResponse>(url, { params: { deviceName: deviceName }})
Do we need timeout handling or other error handling?

2021-05-04 18:40 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
> +                catchError(() => this.manualPersonalization()),
I think we should log the error here and some message that indicates we are falling back to manual personalization after a failed attempt to auto personalize

2021-05-04 19:15 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return Capacitor.isNative;
Sure can, added CapacitorService and updated all the references to Capacitor.isNative

2021-05-04 19:16 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.http.get<DevicePersonalizationResponse>(url, { params: { deviceName: deviceName }})
Right now the error handling is in the AutoPersonalizationService, where it falls back to manual personalization

2021-05-04 19:16 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
> +                catchError(() => this.manualPersonalization()),
Updated the message to reflect that

2021-05-04 19:18 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.http.get<DevicePersonalizationResponse>(url, { params: { deviceName: deviceName }})
What keeps the http `get` from hanging if the endpoint is reachable but not responding for some reason?

2021-05-04 19:22 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.capacitorService.isRunningInCapacitor();
@dankaste Is there any service on the client side that abstracts the client wrapper (cordova, electron, capacitor) that this call could be made to?  Like `wrapper.isAutoPersonalizationSupported()`

2021-05-04 19:23 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.http.get<DevicePersonalizationResponse>(url, { params: { deviceName: deviceName }})
Are you suggesting that we set a specific timeout for this request?

2021-05-04 19:37 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.capacitorService.isRunningInCapacitor();
Maybe DeviceService?

2021-05-04 19:39 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.http.get<DevicePersonalizationResponse>(url, { params: { deviceName: deviceName }})
Yeah, I think a 10 second timeout is reasonable.  You can declare that in the configuration.ts class

2021-05-04 19:52 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +        return this.http.get<DevicePersonalizationResponse>(url, { params: { deviceName: deviceName }})
Sure thing, added

2021-05-04 21:04 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
> +    public getDevicePersonalization(deviceName: string, config: ZeroconfService): Observable<DevicePersonalizationResponse> {
I think it might be confusing to future code travelers for what the difference is between this personalization request and the other existing personalization request which sets up the device data in the dev_* tables.

Should we call the request something like GetPersonalizationParametersRequest  or something along those lines?  This dawned on me when I saw the `Configuration.personalizationRequestTimeoutMillis` parameter and how that could be confusing to someone by not knowing if that was for the actual existing personalize request or something else.

2021-05-04 21:29 UTC, jrmihalick approved these changes

2021-05-05 14:55 UTC, kdelorey approved these changes

2021-05-05 15:18 UTC, merged