Feature/s2 d item notify order icon
JumpMind/openpos-framework pull request #1359
Opened 2021-05-18 12:23 UTC by yuying6688

### Summary
This PR is for PCOM-2278 and PCOM-3155, add order item icon to item order collapsed view. As well as display notify message of item availability checking

### Screenshots
![image](https://user-images.githubusercontent.com/57404096/118650107-13d94580-b7b2-11eb-85ca-45b33e877591.png)

![image](https://user-images.githubusercontent.com/57404096/118650138-1e93da80-b7b2-11eb-9078-fb76c20e680f.png)

![image](https://user-images.githubusercontent.com/57404096/118650156-23f12500-b7b2-11eb-9585-1365eff69928.png)

2021-05-18 12:26 UTC, dankaste requested changes

2021-05-18 12:26 UTC, dankaste commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/SellItem.java
> +    private String iconName;
Lets call this orderIcon or something more specific

2021-05-18 15:12 UTC, kdelorey submitted a review, later dismissed
lgtm.  I just a slight nitpick.

2021-05-18 15:12 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/sell-item.interface.ts
> +    orderIcon:string;
nit: can you add a space between the name and type here.

```suggestion
    orderIcon: string;
```

2021-05-18 15:17 UTC, dankaste submitted a review, later dismissed

2021-05-18 15:21 UTC, yuying6688 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/sell-item.interface.ts
> +    orderIcon:string;
Fixed

2021-05-18 15:47 UTC, kdelorey approved these changes

2021-05-19 12:23 UTC, dankaste approved these changes

2021-05-19 12:24 UTC, merged