Add static hostname fallback to auto-personalization
JumpMind/openpos-framework pull request #1389
Opened 2021-06-10 19:56 UTC by eddielegg-le

### Summary
Add a fallback to the auto-personalization to check for a statically configured hostname and endpoint for the auto-personalization config. If the call fails or the config is null, will fall back to manual personalization.

2021-06-10 20:06 UTC, maxwellpettit approved these changes

2021-06-10 21:05 UTC, jrmihalick requested changes

2021-06-10 21:05 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
> +                    catchError(() => this.personalizeWithHostname())
We don't seem to log errors or any messages when we fail at each place.  Let's add some more logging so we can figure out why we fail when we do.

2021-06-11 12:00 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
> +                    catchError(() => this.personalizeWithHostname())
I think the more detailed logging is going to be on the server side for the most part. I'll see if there's some good client side logging opportunities

2021-06-11 12:28 UTC, jrmihalick approved these changes

2021-06-11 12:31 UTC, merged