Item lookup - made selecting a color change the main image
JumpMind/openpos-framework pull request #1428
Opened 2021-06-25 17:59 UTC by levshunovm

### Summary
This change is needed to make setter in the carousel.component.ts detect changes. It checks only a memory link for an array that is not changing by default. There's a way to override that check itself but it affects performance badly. Let me know if you think it's still better to override the check or if you have a better solution.

2021-06-25 19:04 UTC, chenson42 approved these changes

2021-07-01 12:41 UTC, dankaste requested changes

2021-07-01 12:41 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.ts
> +        this.screen.imageUrls = [].concat(this.screen.imageUrls);
I'm not super crazy about this... no one in the future is going to know why you are doing this.
I'm looking into this real quick. There are ways to manually trigger change detection when we call the setter. I was pretty sure that the ngFor would be looking at the elements in the array and those should be changing.

2021-07-01 12:54 UTC, dankaste approved these changes

2021-07-01 12:54 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.ts
> +        this.screen.imageUrls = [].concat(this.screen.imageUrls);
Never mind... you are right here. I see no better way with how it is currently designed.

2021-07-21 18:11 UTC, merged