Customer enrollment
JumpMind/openpos-framework pull request #1443
Opened 2021-06-30 18:01 UTC by eddielegg-le

> ### PR Instructions - *remove this section*
>
> Release notes are generated off of pull requests.  Please follow these instructions so that your pull request is categorized appropriately. 
>  
> Checklist:
> * Update the title of this pull request to be a concise description of the feature or bug fix
> * Add the label *releasenote* if this PR should be included in the release notes
> * Add the label *majorfeature* if this is a major feature.  If the label exists then the full body of the PR will be included in the major features section of the release notes
> * Add the label *databasechange* if there are database changes associated with this feature
> * Add the label *parameterchange* if there are parameter changes associated with this feature
> * If this PR fixes an issue please list it in the Issues Fixed section.  We'll include the issues fixed in the release notes
> * Please fill out the following sections.  If they don't pertain to this pull request then you can remove the section
> * Please remember to make additional PRs for all relevant branches.  We DO NOT automatically merge branches

### Issues Fixed
List the issues that this PR addresses.  Use [github issue number format](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests).

### Summary
A (sometime wordy) summary of the fix goes here.

### Database Changes
List database changes that apply and note their ramification.  If this section applies then add the label _databasechange_ to your pull request.

### Parameter Changes
Have parameters been added, renamed or removed?  If this section applies then add the label _parameterchange_ to your pull request.

### Screenshots
Screenshots go here.

2021-07-21 18:12 UTC, chenson42 commented
Can this be closed?

2021-07-22 12:17 UTC, eddielegg-le commented
> Can this be closed?

No this is the branch we are staging all the enrollment stuff in. But we could probably point it to 1.11 now, I'll go ahead and do that

2021-07-23 13:51 UTC, blubaugha commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointFilterX.java
> +}
# rEmOvE cOmMeNtEd oUt cOdEs

2021-07-23 13:53 UTC, stojankz commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointFilterX.java
> +}
on that note, can this entire file be deleted?

2021-07-23 13:54 UTC, mmichalek commented on openpos-service/src/main/java/org/jumpmind/pos/service/EndpointFilterX.java
> +}
Yes, it can. My bad

2021-07-23 14:14 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/membership-plan-details-dialog/membership-plan-details-dialog.component.html
> +<div>
Is this div needed?

2021-07-23 14:14 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/program-plan-details/program-plan-details.component.html
> +            <app-plan-details-display [plan]="plan"></app-plan-details-display>
plan plan plan plan plan plan plan so many plans

2021-07-23 14:14 UTC, jchirico8 commented on openpos-test/openpos-test.iml
> +          <root url="jar:///Users/mmichalek/.gradle/caches/modules-2/files-2.1/com.h2database/h2/1.4.199/7bf08152984ed8859740ae3f97fae6c72771ae45/h2-1.4.199.jar!/"/>
Am I going to have to move my gradle caches to a Users/mmichalek folder as well?

2021-07-23 14:17 UTC, mmichalek commented on openpos-test/openpos-test.iml
> +          <root url="jar:///Users/mmichalek/.gradle/caches/modules-2/files-2.1/com.h2database/h2/1.4.199/7bf08152984ed8859740ae3f97fae6c72771ae45/h2-1.4.199.jar!/"/>
😛

2021-07-23 14:20 UTC, stojankz requested changes

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/program-plan-select-dialog/program-plan-select-dialog.component.spec.ts
> +
since this does not do anything, can it be removed?

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/program-plan-select-dialog/program-plan-select-dialog.component.spec.ts
> +        describe("configuration keybinds are disabled", () =>{
this should use single quote (') not double ("). And on that note, there are a lot of places I've noticed " where it should be '. If you're not, I'd recommend using tslint or some other lint tool for angular.

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/program-plan-select-dialog/program-plan-select-dialog.component.spec.ts
> +            let menuItem: IActionItem = {keybind: "Enter"} as IActionItem;
"Enter" -> 'Enter'

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/program-plan-select-dialog/program-plan-select-dialog.component.ts
> +
This can be removed, PosScreen already has this default buildScreen() function that does nothing

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/plan-details-display/plan-details-display.component.html
> +                *ngIf="plan.iconImageUrl"
can we fix format on this?

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/plan-details-display/plan-details-display.interface.ts
> +}
is this file needed/is it for future use? Doesn't have anything in it

2021-07-23 14:20 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/program-plan-details/program-plan-details.component.spec.ts
> +                iconText: "iconText",
again, should be using ' for string rather than "

2021-07-23 17:19 UTC, Ganeshk01 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
>      membershipLabel: String;
'String' should start with small letter('string') in typescript

2021-07-27 17:35 UTC, stojankz submitted a review, later dismissed

2021-07-27 19:40 UTC, stojankz approved these changes

2021-07-27 19:40 UTC, merged