Feature/api tokens and rest path
JumpMind/openpos-framework pull request #1491
Opened 2021-07-27 14:48 UTC by mzipay

### Summary
Support for API token auth and "/rest" context path (rebased onto 1.12).

2021-07-28 14:35 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +            LOG.warn(ex.toString());
Let's change this to something like
` LOG.warn("Failed to find class " + className, ex); so we get the whole stack trace.`

2021-07-28 14:35 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +    private static final Logger LOG = LoggerFactory.getLogger(RestApiSupport.class);
Can replace with @Slf4j annotation on the class, and use "log" variable.

2021-07-28 14:35 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +public final class RestApiSupport {
Can this be a Spring bean vs. static singleton?

2021-07-28 16:36 UTC, mzipay commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +            LOG.warn(ex.toString());
An entire stack trace is a bit much in this case.  Contextually, the log entry as-is will already note where the incident occurred (RestApiSupport), what went wrong (ClassNotFoundException) and the FQCN of the class that wasn't found. A full stack trace here will not provide anything additionally meaningful (and may actually be quite confusing to a log viewer as this is simply a WARN-level record, not an error).
Are you sure you want a full stack trace here?

2021-07-28 16:48 UTC, mzipay commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +public final class RestApiSupport {
It isn't a singleton - there is no instance, just a group of interrelated (static) utility methods that are used in lambdas and one factory method. It does not have state; not really a good candidate for a bean.

2021-07-28 16:50 UTC, mzipay commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +            LOG.warn(ex.toString());
Also note that this is used in the context of a collection stream - one of the reasons it's kept short and sweet.

2021-07-28 16:51 UTC, mzipay commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +    private static final Logger LOG = LoggerFactory.getLogger(RestApiSupport.class);
Done.

2021-07-28 17:30 UTC, mmichalek requested changes

2021-07-28 17:30 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +            LOG.warn(ex.toString());
Just use ClassUtils.loadClass() instead please.

2021-07-28 17:30 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +public final class RestApiSupport {
We cannot easily plug in replacement code for static methods, whereas we can override object-based beans.  If this can work as a bean, please make it a bean.

2021-07-28 20:42 UTC, mzipay commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +public final class RestApiSupport {
I think we should discuss this further, because I don't quite follow why this would be a bean (or need to be).  The package org.jumpmind.pos.util is full of classes just like this one, doing the same thing (collecting related stateless static utility methods). What is the reasoning behind turning _this_ utility class into a bean? Perhaps I don't understand the motivation or some overarching goal.

Worth noting there are already mechanisms here for changing behavior in the spring beans that _use_ this utility. For example see the overloads for requestMappingToUrlPattern and also the fact that the injectable ApiTokenAutoConfiguration#restApiScanner(String) bean simply delegates to RestApiSupport#newRestApiScanner - which is trivial to modify post-construction or even to completely swap out the entire impl.

Can you take a look at the `@Bean` methods in ApiTokenAutoConfiguration? That's where the "replacement" of any of this utility logic would occur. I think that may satisfy what (I think) you're looking for here.

2021-07-28 21:30 UTC, mzipay commented on openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
> +            LOG.warn(ex.toString());
Done.

2021-08-03 14:21 UTC, mmichalek approved these changes

2021-08-03 15:24 UTC, jrmihalick commented
Had a conversation with Matt about these endpoints which are called directly from angular client code:

**ping**: openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/session.service.ts
**fileUpload**: openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/file-upload.service.ts
**fetchMessage**: openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/fetch-message.service.ts
**personalize**: openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts

personalize and ping are the most important to be excluded from the token api.  fileUpload is only used by one retailer on an old version of openpos.  fetchMessage was written by @dankaste , so I am not sure how it is used.

2021-08-03 15:24 UTC, jrmihalick approved these changes

2021-08-03 19:06 UTC, merged