Fix showing build version
JumpMind/openpos-framework pull request #1500
Opened 2021-07-30 10:33 UTC by mdruzhin

### **Issues Fixed**

[PCOM-3822](https://jira.ae.com/browse/PCOM-3822)

### **Summary**

Delete some styles for showing build version on top of the main application screen

### **Screenshots**

<img width="359" alt="Screenshot 2021-07-30 at 2 27 14 PM" src="https://user-images.githubusercontent.com/82650510/127640088-9a19e941-56a1-4fcd-b09d-5046b12c0ffa.png">

2021-07-30 14:45 UTC, jchirico8 approved these changes

2021-07-30 14:58 UTC, blubaugha requested changes
Looks like this causes some style problems, on mobile and tablet devices, trying to fit all of that content in there. I'm not sure what the best solution is yet...

**ELO POS - Portrait**
`CSS Class = desktop-portrait`

<img width="316" alt="elopos-portrait- desktop-portrait" src="https://user-images.githubusercontent.com/3991426/127671645-c21f94c7-626a-43ba-8e4e-ae36d9458d4e.png">

**iPad Pro - Portrait**
`CSS Class = desktop-portrait`

<img width="422" alt="ipad-pro-portrait- desktop-portrait" src="https://user-images.githubusercontent.com/3991426/127671894-1a0a73a1-b81a-4a0e-9bd2-589abe0eb537.png">

**iPad - Portrait**
`CSS Class = desktop-portrait`

<img width="389" alt="ipad-portrait- desktop-portrait" src="https://user-images.githubusercontent.com/3991426/127671942-e774439e-71ea-4a72-a9e5-08b6704a7c2a.png">

**Zebra TC52 (Retna) - Portrait**
`CSS Class = mobile-portrait`
<img width="647" alt="zetratc52retna-portrait- mobile-portrait" src="https://user-images.githubusercontent.com/3991426/127672058-b60163af-f7f4-4892-8d76-aedc23e7c38f.png">

**Zebra TC 52 - Portrait**
`CSS Class = mobile-portrait`
<img width="292" alt="zebratc52-portrait- tablet-portrait" src="https://user-images.githubusercontent.com/3991426/127672150-85036cd5-6c64-4ab2-a167-8aa2eaf17576.png">

2021-08-02 11:35 UTC, mdruzhin commented
@blubaugha As a first option, we can make It not display in some situations:

- Mobile devices - build number is not displayed
- Tablet devices - build number is displayed only in the tablet-landscape style
- Desktop devices - build number is displayed only in the desktop-landscape style

It is fixed not correct display build version on some devices.

Also this bug was related with resolution on the device. For example, my laptop determine as tablet device in the application. (Earlier, build version was full turned off for tablet devices)

I tested it in the firebug and I got following results with my changes described above:

### **Mobile Devices (In example IPhone 6/7/8):**

_Css style -  mobile-landscape_

<img width="668" alt="Mobile L" src="https://user-images.githubusercontent.com/82650510/127854726-ce7db770-0cd2-425f-8db6-d50f1a3374ad.png">

_Css style -  mobile-portrait_

<img width="353" alt="Mobile P" src="https://user-images.githubusercontent.com/82650510/127854754-55acb4eb-b2d2-4ccc-ab9e-93073813bfce.png">

### **Tablet Devices (In example IPad):**

_Css style -  tablet-landscape_

<img width="770" alt="IPad L" src="https://user-images.githubusercontent.com/82650510/127854778-9d843e50-1d1a-4f47-8b72-1fcd54cfb445.png">

_Css style -  tablet-portrait_

<img width="576" alt="IPad P" src="https://user-images.githubusercontent.com/82650510/127854825-a8e8a727-3202-4275-ad5b-e236f610b790.png">

### **Desktop Device, resolution 1366x1024:**

_Css style -  desktop-landscape_
<img width="1023" alt="IpadPro L" src="https://user-images.githubusercontent.com/82650510/127855009-ec090ca3-4588-4cb6-8c1d-dd5a92c77139.png">

_Css style -  desktop-portrait_
<img width="765" alt="IpadPro P" src="https://user-images.githubusercontent.com/82650510/127855024-196ee75a-8958-42d0-a7c1-649674cd71f4.png">

### **Desktop Device, resolution 1920x1080:**

_Css style -  desktop-landscape_
<img width="961" alt="Desktop L" src="https://user-images.githubusercontent.com/82650510/127855041-f6414416-037d-4845-a71d-4d304f1468fc.png">

_Css style -  desktop-portrait_
<img width="542" alt="Desktop P" src="https://user-images.githubusercontent.com/82650510/127855062-465a8271-ad4a-4ae0-bf28-0c51ccc6ed8f.png">

2021-08-02 14:17 UTC, chenson42 commented
Should we just remove the text "AEO Commerce"?

2021-08-02 14:55 UTC, mdruzhin commented
@chenson42 This is good idea, thank you, it will resolve problems on the devices with low resolution, but we'll be still having problem with mobile devices in the portrait view. For mobile devices with this changes It will look like this: 

_mobile-landscape_
<img width="669" alt="Screenshot 2021-08-02 at 6 43 09 PM" src="https://user-images.githubusercontent.com/82650510/127879763-a5851a63-225e-4100-8b6d-16913042d5a2.png">

_mobile-portrait_
<img width="359" alt="Screenshot 2021-08-02 at 6 31 13 PM" src="https://user-images.githubusercontent.com/82650510/127879554-6379cc68-84d5-43e3-891e-8a407d4f11f7.png">

First line with device detail too long for mobile. Maybe we should cut off some part line?  For example like this:

_mobile-portrait_
<img width="355" alt="Screenshot 2021-08-02 at 6 51 00 PM" src="https://user-images.githubusercontent.com/82650510/127881013-685e582a-c0b0-45e6-8c71-9fc69bbfb6fb.png">

2021-08-02 15:01 UTC, chenson42 commented
In mobile, the device mode stuff isn't really relevant anyways so I think what you are proposing makes sense

2021-08-02 20:15 UTC, blubaugha submitted a review, later dismissed

2021-08-02 20:25 UTC, jchirico8 requested changes

2021-08-02 20:25 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
> +    {{(systemInfo$ | async)?.line2.replace("AEO Commerce", "")}}
This is not right. We shouldn't have a direct reference to AEO in openpos code. You'll have to find where this text is added to line2 and add a condition in there to not include this text.

2021-08-02 21:34 UTC, mdruzhin commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
> +    {{(systemInfo$ | async)?.line2.replace("AEO Commerce", "")}}
I agree with you. I'm thinking about spliting line2 on two parts - line2App and line2Version. I'm not sure, that we have information about device view in java code (landscape or portrait), so I think, It will be not bad option.

2021-08-03 05:42 UTC, mdruzhin commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
> +    {{(systemInfo$ | async)?.line2.replace("AEO Commerce", "")}}
@jchirico8 I think we can just add a short version for line2 without splitting the main line2. This option is better than the one I described above.

2021-08-04 09:14 UTC, mdruzhin commented
@blubaugha @chenson42 @jchirico8 Please, check my PR in the Commerce - https://github.com/JumpMind/commerce/pull/4335. Also, I updated screenshots in the initial comment with results of changes

2021-08-04 13:16 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
> +  <span *ngIf="rightStatus.classList.value.includes('-portrait'); else regularLine2">
does the mobile layout also include the -portrait class?

2021-08-04 13:44 UTC, mdruzhin commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
> +  <span *ngIf="rightStatus.classList.value.includes('-portrait'); else regularLine2">
yes, we have portrait class for mobile devices:
<img width="281" alt="Screenshot 2021-08-04 at 5 30 32 PM" src="https://user-images.githubusercontent.com/82650510/128191337-57f08bfc-e04e-4828-bf9f-450e75465725.png">

2021-08-04 13:50 UTC, jchirico8 approved these changes

2021-08-04 14:20 UTC, blubaugha approved these changes

2021-08-05 07:58 UTC, merged