Action sync support
JumpMind/openpos-framework pull request #1606
Opened 2021-09-17 18:44 UTC by mmichalek

### Issues Fixed
This PR modifies the framework to link actions with the current state of the state machine.  If the state machine gets out of sync, and an action from a previous screen/state is raised, than the state machine will log and throw away that action (and refresh the screen.)

This change required client side changes to reports, because reports were sending down the action name as the report name, and then assigning that report name to the action data.  This changes things so the actionName/data go down and come up the same way.

2021-09-17 19:15 UTC, jrmihalick requested changes

2021-09-17 19:15 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ActionHandlerImpl.java
> +                || actionContext.getSyncState().equals(GLOBAL_ACTION)
Should this perhaps instead be a boolean on the actionContext, `isGlobalAction()` instead of overloading the purpose of the syncState?

2021-09-17 19:15 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ActionSyncMessagePropertyStrategy.java
> +            if (stateLabel != null && !actionItem.getAction().contains(SYNC_STATE_DIVIDER)) {
This logic
`actionItem.getAction().contains(SYNC_STATE_DIVIDER)` is used in at least a couple of places, should it be centralized somewhere in a utility class or the like?

2021-09-17 19:15 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/LoggingStateManagerObserver.java
> +    private String getScreenSequence(UIMessage screen) {
Mucho thanko. 👍

2021-09-17 19:15 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
> +            return;
Should something be logged here or will that happen downstream from here?

2021-09-17 19:24 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/ActionItem.java
> +    protected Object data;
Wonder if we should use `defaultPayload` for this instead?  Tough call, but it's close to the same usage.

2021-09-17 19:24 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action-item.ts
> +    data?: string;
See my comment below about `defaultPayload`.  It's on the `IActionItem` interface here.

2021-09-20 13:10 UTC, mmichalek commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action-item.ts
> +    data?: string;
Agreed, I will go with defaultPayload.

2021-09-20 13:13 UTC, mmichalek commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ActionHandlerImpl.java
> +                || actionContext.getSyncState().equals(GLOBAL_ACTION)
So the "sync state" is supposed to be slightly more abstract than a specific state name.  Maybe there's a better name.  I was thinking the future I wanted to leave this open even for a little more data e.g. 
Next@StateName
Next@7804d7 // e.g. a hash pointing to more complex state data
Next@StateName:otherData

2021-09-20 13:14 UTC, mmichalek commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ActionSyncMessagePropertyStrategy.java
> +            if (stateLabel != null && !actionItem.getAction().contains(SYNC_STATE_DIVIDER)) {
Agreed

2021-09-20 13:14 UTC, mmichalek commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/LoggingStateManagerObserver.java
> +    private String getScreenSequence(UIMessage screen) {
👍

2021-09-20 13:14 UTC, mmichalek commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
> +            return;
Yes - the checkActionSync will log a WARN in this case.

2021-09-20 13:14 UTC, mmichalek commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/ActionItem.java
> +    protected Object data;
Ok, will switch to defaultPayload.

2021-09-20 13:45 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ActionHandlerImpl.java
> +                || actionContext.getSyncState().equals(GLOBAL_ACTION)
Ok, I see. `syncyThingy`

2021-09-20 19:15 UTC, jrmihalick commented on openpos-flow/src/main/java/org/jumpmind/pos/core/flow/LoggingStateManagerObserver.java
>          logTranistionStep(transition, currentTransitionStep);
You didn't modify this code, but I just noticed the method has a typo in it.  Can fix some other time, just FYI in case you want to fix it now.

2021-09-21 13:00 UTC, jrmihalick submitted a review, later dismissed

2021-09-21 20:20 UTC, jrmihalick approved these changes

2021-09-21 20:21 UTC, merged