Feature/customer accounts
JumpMind/openpos-framework pull request #1723
Opened 2021-11-03 20:38 UTC by stojankz

### Summary
Openpos-framework PR for customer account and customer subscription logic being pulled from 1.12 into master. List of PRs cherrypicked and pulled in can be found here: 

https://docs.google.com/spreadsheets/d/1fd6ig9cofc6fXI2nlEa2RGqB61MAx2Q0RAbQVhNsF3Y/edit?usp=sharing

### Screenshots
Commerce Demo:
![customer-subscription-demo](https://user-images.githubusercontent.com/6811136/140188644-24fe3cb7-0b06-4716-b3da-875005ae74ad.gif)

Commerce Demo Fashion:
![customer-subscription-demo-fashion](https://user-images.githubusercontent.com/6811136/140188704-d4ea28f9-a9a0-4290-8e97-1b187ecdd61c.gif)

2021-11-03 23:57 UTC, chenson42 submitted a review, later dismissed

2021-11-04 14:47 UTC, kdelorey submitted a review, later dismissed

2021-11-04 14:47 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/enrollment-confirmation-dialog/enrollment-confirmation-dialog.html
> +                    <div [innerHTML]="screen.message"></div>
Thoughts on the `screen.message` (and similar) being markdown instead of RAW html and rendered with the pipe? This will likely result in an easier time with any style and for any really complex things that markdown can't handle you can still embed HTML into the markdown.

2021-11-04 15:32 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/enrollment-confirmation-dialog/enrollment-confirmation-dialog.html
> +                    <div [innerHTML]="screen.message"></div>
does the markdown-formatter pipe work if screen.message is html? I'm not entirely sure behind the reasoning but I believe with some of the details shown on a lot of these dialogs, the idea was to have them be completely customizable in how they look and so that message is coming from a database table like cust_customer_program_copy

2021-11-04 15:38 UTC, r-cochran submitted a review, later dismissed

2021-11-04 15:49 UTC, r-cochran commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/enrollment-confirmation-dialog/enrollment-confirmation-dialog.html
> +                    <div [innerHTML]="screen.message"></div>
that is correct, there was a desire from the client for the ability to fully create the content in the various copy locations (program / plan) for content/styling/layout. 

If the markdown pipe will let all the content through as it works today and do replacements for anything that is markdown then I don't see an issue with making this change. Though I feel like if the person making the copy later on accidentally hits on any of the markdown syntax they will have a headache debugging it.

2021-11-04 17:20 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/enrollment-confirmation-dialog/enrollment-confirmation-dialog.html
> +                    <div [innerHTML]="screen.message"></div>
It _should_ allow you to a mix of markdown and html, but if I'm behind honest I don't have the details of that on me. I assumed customizing the HTML with a bunch of styles would be a pain point that would be alleviated with markdown. Its probably not worth throwing wrenches into the solution at the moment however, maybe something we explore down the road. Lets leave it alone for now.

2021-11-04 18:09 UTC, jchirico8 requested changes

2021-11-05 19:38 UTC, jchirico8 approved these changes

2021-11-05 19:57 UTC, r-cochran approved these changes

2021-11-05 20:56 UTC, jchirico8 approved these changes

2021-11-05 21:08 UTC, merged