Feature/tender aecc
JumpMind/openpos-framework pull request #1777
Opened 2021-11-30 20:38 UTC by chadhav-ae

### Issues Fixed
Adding a Feature UI of Tender Shopping Pass which includes expiry date with card number

2021-12-01 16:06 UTC, jchirico8 requested changes

2021-12-01 16:06 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/prompt-form-part-addition.component.ts
> +        if (this.screenData.isRequiredInputField !== false) {
This is recreating a lot of logic from `form-builder.service.ts`. Is it necessary to do all of this again?

2021-12-01 16:06 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/min-date.validator.ts
> +export function minDateValidator(minDate: Date): ValidatorFn {
Nearly this exact validator exists in CustomDateValidators. Try to use that instead of recreating it

2021-12-01 16:06 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/prompt-form-part-addition.component.ts
> +        if (this.screenData.isRequiredInputField !== false) {
It actually looks like most of this was copied from prompt-form-part. Can you help me understand what the difference is that caused us to need a new component?

2021-12-01 16:42 UTC, chadhav-ae commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/PromptWithInfoScanAndExpiryDateUIMessage.java
> +    public boolean isCardExpiryDateEnabled() {
okay Joe i will change it to @Data .

2021-12-01 16:47 UTC, chadhav-ae commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/prompt-form-part-addition.component.ts
> +        if (this.screenData.isRequiredInputField !== false) {
Yes we discussed on this, after understand on the UI we decided not to use the old one, rather create a separate one that includes the expiry date. Let me know if you think we can use the old prompt part. I have to discuss again on that.

2021-12-01 16:48 UTC, chadhav-ae commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/min-date.validator.ts
> +export function minDateValidator(minDate: Date): ValidatorFn {
Okay i will try that. I didn't know that it exist. Thanks for letting me know.

2021-12-01 17:11 UTC, jchirico8 commented
@chadhav-ae could you post a screenshot in the description of the dialog?

2021-12-01 17:16 UTC, chadhav-ae commented
> @chadhav-ae could you post a screenshot in the description of the dialog?

added

2021-12-02 03:49 UTC, kdelorey commented
This is for credit cards correct? Credit cards don't usually have a MM/DD/YYYY format. It's usually MM/YY but I think MM/YYYY would be acceptable too.

2021-12-02 03:55 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/prompt-form-part-addition.component.ts
> +        if (this.screenData.isRequiredInputField !== false) {
I think ideally a new prompt should be made that can support accepting multiple inputs on a single form, but it seemed like that would be a much larger scope.

Anyways, I think we just need to rename some of these things for now. It seems very credit card specific, so I would name it as such for now.

2021-12-02 12:33 UTC, chadhav-ae commented
> This is for credit cards correct? Credit cards don't usually have a MM/DD/YYYY expiration format. It's usually MM/YY but I think MM/YYYY would be acceptable too.

Hi Kevin, This is for Shopping Pass, Shopping pass has expiry date printed as MM/dd/yyyy. So, we used the same that is printed in shopping pass so that cashier won't be able to get confused

2021-12-02 12:35 UTC, chadhav-ae commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/prompt-form-part-addition.component.ts
> +        if (this.screenData.isRequiredInputField !== false) {
Okay Kevin, I will rename it on specific card type. As gift card would also be using the same. So, i will rename it as a card specific.

2021-12-02 19:51 UTC, jchirico8 submitted a review, later dismissed

2021-12-02 20:26 UTC, chadhav-ae commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part-addition/min-date.validator.ts
> +export function minDateValidator(minDate: Date): ValidatorFn {
done with the changes

2021-12-02 20:27 UTC, chadhav-ae commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/PromptWithInfoScanAndExpiryDateUIMessage.java
> +    public boolean isCardExpiryDateEnabled() {
updated as per Joe suggestion

2021-12-03 14:06 UTC, kdelorey approved these changes

2021-12-03 14:10 UTC, jchirico8 approved these changes

2021-12-03 14:50 UTC, merged