Feature/cordova app auto exit
JumpMind/openpos-framework pull request #1793
Opened 2021-12-07 04:31 UTC by shiljo-litmus7

Issues Fixed
New Cordova Android plugin to close the app programatically. The plugin will subscribe to message with APP_MANAGEMENT as Proxy type from server and upon receiving the message, will close the app using the plugin
This capability is created as part of this item  https://petcoalm.atlassian.net/browse/PDPOS-6897

Summary
 A new Cordova Android plugin for closing the app

2021-12-07 14:45 UTC, jrmihalick requested changes

2021-12-07 14:45 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/cordova-plugins/auto-exit.ts
> +        return Observable.create((initialized: Subject<string>) => {
TS lint usually warns me not to use `Observable.create` and now use new `Observable<string>`.  Not sure why its deprecated.  https://stackoverflow.com/questions/55539103/angular-create-is-deprecated-use-new-observable-instead

2021-12-07 14:45 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/cordova-plugins/auto-exit.ts
> +            this.sessionService.getMessages('Proxy').pipe(
We don't need to use Proxy messages here.  You can search on this in the client project and find a lot of examples...  `sessionService.getMessages(`

2021-12-07 14:45 UTC, jrmihalick commented on openpos-server-core/src/main/java/org/jumpmind/pos/server/model/ProxyTypeConstants.java
> +    public static final String APP_MANAGEMENT = "AppManagement";
See prior comments, we don't need to use a Proxy message here.

2021-12-08 15:40 UTC, shiljo-litmus7 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/cordova-plugins/auto-exit.ts
> +        return Observable.create((initialized: Subject<string>) => {
Done

2021-12-08 15:40 UTC, shiljo-litmus7 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/cordova-plugins/auto-exit.ts
> +            this.sessionService.getMessages('Proxy').pipe(
Done

2021-12-08 15:41 UTC, shiljo-litmus7 commented on openpos-server-core/src/main/java/org/jumpmind/pos/server/model/ProxyTypeConstants.java
> +    public static final String APP_MANAGEMENT = "AppManagement";
Done

2021-12-08 15:44 UTC, jrmihalick approved these changes

2021-12-08 18:42 UTC, merged