Startup 2.0
JumpMind/openpos-framework pull request #1815
Opened 2021-12-20 15:02 UTC by kdelorey

# Summary
This proposes new changes to the startup sequence in order to make it easier to troubleshoot, unit test, and comprehend. Previously the startup system worked by chaining together really noise observable sequences and their completion signaled their success. This worked great but relied on heavy knowledge of RxJS operators to properly understand and even with advanced knowledge, some tasks were very difficult to comprehend and subsequently troubleshoot.

Overall it was a really chatty stream as the stream contained splash screen messages, most often they were too verbose containing log messages. This chatty-ness made it difficult to do proper unit testing on startup tasks.

## Interface
The new `StartupTask` interface contains only a single `execute()` method and is permitted to return a synchronous `void`, an asynchronous `Promise<void>` or an `Observable<any>`. The task runner will understand each type and act accordingly. It will be suggested that new tasks stick to `void` or `Promise<void>` when possible.

Implementations of `StartupTask` should always be a `@Injectable()` in order to properly support Dependency Injection. If it is not, task execution will fail.

The name of the task is automatically inferred from the name of the class.

## Startup Sequence
The priory scheme of tasks as been dropped in favor of just globally listing them in sequence order. In order to add a new task, you should add it to the `startupSequence` in `startup-sequence.ts`. This list accepts injection tokens or combinators.

### `all()` Combinator
The `all(...)` combinator requires all of the listed task to complete successfully or execution of the combinator fails. The combinator fails at the first error.

### `oneOf()` Combinator
The `oneOf(...)` combinator will run tasks sequentially and completes when the first task finishes successfully. If all tasks fail execution, the combinator fails to execute.

### `optional()` Combinator
The `optional()` combinator will run the contained task, but succeeds on failure and success.

### `withSplashMessage()` Combinator
The  `withSplashMessage()` will simply wrap a task and during execution it will set the displayed splash screen message to a user friendly string. When execution is finished, the splash screen message is popped off.

2021-12-20 18:48 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-controller.service.ts
> +export type StartupControllerState = true | 'in-progress' | false | 'error';
Would this work the same?
```suggestion
export type StartupControllerState = boolean | 'in-progress' | 'error';
```

2021-12-20 18:48 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-controller.service.ts
> +        this._status = { completed: 'in-progress' };
This might just be preference but I'm thinking why initialize the property above if you'll overwrite it with a new object instead of just changing the status
```suggestion
        this._status.completed = 'in-progress';
```

2021-12-20 18:48 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-controller.service.ts
> +        this._status = { completed: true };
Same thing here. Why create a whole new object each time
```suggestion
        this._status.completed = true;
```

2021-12-20 18:48 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task.ts
> +      console.log(`startup task '${getTaskName(this._task)}' failed to execute; ignoring optional task`);
does this log need the task name in it? The onfOf failure message doesn't I assume because there is a log in performTask that would tell you what task is running right before the failure

2021-12-20 20:27 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-controller.service.ts
> +export type StartupControllerState = true | 'in-progress' | false | 'error';
Yeah it should; not sure why I did it this way.

2021-12-20 20:35 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task.ts
> +      console.log(`startup task '${getTaskName(this._task)}' failed to execute; ignoring optional task`);
I think this was remnants of me debugging. I think I do want to leave it will always successfully execute whereas `oneOf()` can fail. So it might be nice to know that underneath that the task actually failed, so I think I'd like to change this to a `debug` level message. I do think `oneOf` logging could be improved too. I'll look into it.

2021-12-20 20:40 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-controller.service.ts
> +        this._status = { completed: 'in-progress' };
I actually prefer the state as one whole immutable object (which I failed to actually do). Changes to to the object should be detected as a whole not as two seperate changes. It's also a little bit for safety. Changing the state should force you to intentionally attach an error or not.

2021-12-20 23:13 UTC, jrmihalick requested changes

2021-12-20 23:13 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
> +export class ZeroConfPersonalizationStartupTask implements StartupTask {
We're going to need an Auto Personalization base class that does that part of calling the server to get the personalization parameters.  That could then be extended by this task and another that I will need to port over from 1.13 which uses the EnterpriseConfig to personalize.  The only difference really between those two tasks is where the URL used for attempting to get the auto personalization params is coming from.  While you are in here doing this, might as well prepare for it now and set up the base class now.  😄

2021-12-20 23:13 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-sequence.ts
> +export let startupSequence = all(
This is a big improvement, better than having an `order` attribute.  👍

2021-12-20 23:13 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-sequence.ts
> +export let startupSequence = all(
Plus we'll be able to add new combinators.  Nice.

2021-12-21 15:22 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/audio.startup-task.ts
> +        console.debug('begin preloading audio configuration');
There are some side effects to consider. Automatically augmenting the console logging will cause the little portion of the chrome devtools that shows where the it was logged from to be overwritten with something useless. This is probably acceptable since you want to include the task name in the log message. It will also impact everything logging from services and such while inside of a task. It would look something like:

```
[SomeStartupTask] About to call some service
[SomeStartupTask] Okay I'm in the service now doing stuff.
```

Not sure if that's the desired effect you want?

Another option to avoid all these side effects is to manually place this information within log message. This would be pretty tedious and annoying to do in my opinion, especially considering the information is already present between begin and end log blocks.

We could also roll a logger that is understands some scope?

2021-12-21 15:36 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
> +export class ZeroConfPersonalizationStartupTask implements StartupTask {
Sure, I also realize that I think I accidently forgot the personalize with query params so I'll do that too.

2021-12-21 16:37 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
> +export class ZeroConfPersonalizationStartupTask implements StartupTask {
Done, but you'll have to modify it to support your enterprise stuff which doesn't appear to be in master.

2021-12-21 17:17 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/audio.startup-task.ts
> +        console.debug('begin preloading audio configuration');
![image](https://user-images.githubusercontent.com/2295721/146971707-f3a9aa0f-f695-486f-8e19-fc09132b8c60.png)

I did the first option for now, we can improve it later if you want.

2021-12-21 17:42 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/audio.startup-task.ts
> +        console.debug('begin preloading audio configuration');
@kdelorey Looks good, thanks.

2021-12-21 17:42 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
> +export class ZeroConfPersonalizationStartupTask implements StartupTask {
@kdelorey Yep, no problem

2021-12-21 17:51 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
> +                CONFIGURATION.autoPersonalizationServicePath
Why hard-code read this out of configuration instead of passing in as a parameter?  When I port over the EnterpriseConfig changes, am I supposed to directly set `CONFIGURATION.autoPersonalizationServicePath` with the value I read from the Enterprise config?

2021-12-21 17:58 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
> +                CONFIGURATION.autoPersonalizationServicePath
This is just what existed before and I didn't really give it much thought. I think @eddielegg-le or somebody added it to support some other way of auto personalizing. Wasn't really sure what your needs are so I just ripped a possibly common chunk out into a base class as requested. You might just modify it to fit your needs.

Doesn't your enterprise variant use the same `personalizeMe` endpoint? Is that not what this configuration variable points to?

2021-12-21 18:15 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
> +                CONFIGURATION.autoPersonalizationServicePath
Yes, it does use the same personalizeMe endpoint, but the actual URL of the endpoint will vary depending on the environment.  I use the enterprise config to read that URL value.  If you prefer, I can refactor later, but I would probably just change this task to pass in the URL as a param.

2021-12-21 18:18 UTC, eddielegg-le commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
> +                CONFIGURATION.autoPersonalizationServicePath
Yeah that was what we decided on for Petco for the zero conf personalization. Not even sure it's used now?

2021-12-21 18:20 UTC, kdelorey commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
> +                CONFIGURATION.autoPersonalizationServicePath
I would just refactor it to your needs later. I'm also partially biased because my hands are tied up with AEO stuff currently so I probably won't touch this PR again for a long while.

2021-12-21 18:46 UTC, jrmihalick approved these changes

2021-12-21 20:03 UTC, merged