To display Savings Calculator in RR Loyalty Panel
JumpMind/openpos-framework pull request #2060
Opened 2022-03-08 02:17 UTC by devallur

to display savings message as below 
<img width="475" alt="Screen Shot 2022-03-07 at 6 49 34 PM" src="https://user-images.githubusercontent.com/92107513/157152926-47d50f66-7ceb-4414-ba1e-7fba930e656b.png">
<img width="920" alt="Screen Shot 2022-03-07 at 8 52 42 PM" src="https://user-images.githubusercontent.com/92107513/157152960-74eee2af-b54f-4f98-8003-1bbd56453c9b.png">

2022-03-08 15:03 UTC, VodianytskyiVI commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
> +                    <div  class="savingsCalculator">
Please remove extra space after div

2022-03-08 15:04 UTC, VodianytskyiVI requested changes

2022-03-08 15:04 UTC, VodianytskyiVI commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                    "SavingsCalculator SavingsCalculator";                ;
Please remove redundant ';' symbol

2022-03-08 15:20 UTC, devallur commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                    "SavingsCalculator SavingsCalculator";                ;
removed extra ;

2022-03-08 15:38 UTC, blubaugha commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                 color: #FF0000;
Instead of hard-coding the color here, you can remove this line and set it from the current theme like this:

* Remove `color`: #ff0000`
* Add this to the `_sale-total-panel-theme.scss` file:
```
// Put this with other variable declarations at the top of the file
$warn: map-get($theme, warn);

// Use kebab-case instead of pascal case
.savings-calculator {
    color: mat-color($warn);
}
```

2022-03-08 19:15 UTC, devallur commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                 color: #FF0000;
Added the color from theme palatte instead of hardcoding

2022-03-08 19:15 UTC, devallur commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                .savingsCalculator {
done

2022-03-09 06:41 UTC, VodianytskyiVI approved these changes

2022-03-09 15:32 UTC, blubaugha approved these changes

2022-03-09 16:00 UTC, merged