Merge PLCC Apply feature into releases/2.7
JumpMind/openpos-framework pull request #2102
Opened 2022-03-16 21:18 UTC by VodianytskyiVI

Merge PLCC Apply feature into releases/2.7.

2022-03-17 16:24 UTC, jchirico8 requested changes

2022-03-17 16:24 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/show-errors/show-errors.component.ts
> +        (this.control.dirty) || !!this.error;
```suggestion
        this.control.dirty || !!this.error;
```

2022-03-17 16:24 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/mobile-loyalty-part/mobile-loyalty-part.component.html
> +            <div responsive-class *ngIf="screenData.savingsCalculatorMessage" class="savings-calculator">
Let's make this more generic so it can be used for any kind of alert message. Change the naming to alertMessage or attentionMessage since it exists to draw the cashiers attention to something about the customer

2022-03-17 16:24 UTC, jchirico8 commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/PlccApplicationMessage.java
> +    @JsonProperty("isActiveOnCustomerDisplay")
Is this needed? The value is the same as the variable name so I wouldn't think you need this

2022-03-17 16:24 UTC, jchirico8 commented on openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/PlccApplyMessage.java
> +public class PlccApplyMessage extends Message {
This is the same as PlccApplicationMessage. Delete one and remove JsonProperty from the one that's saved if it's not needed

2022-03-18 14:45 UTC, devallur commented
> /var/lib/jenkins/workspace/openpos-framework_PR-2102/openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-form-field/dynamic-form-field.component.ts:42:1 ERROR: 42:1 no-trailing-whitespace trailing whitespace

Lint errors resolved

2022-03-18 15:07 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/loyalty-sale-part.service.ts
> +    providedIn: 'root',
This is redundant with the declaration in CoreModule. I'd prefer to remove this provider, assuming it still works okay

2022-03-18 15:07 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/mobile-loyalty-part/mobile-loyalty-part.component.html
> +            <div responsive-class *ngIf="screenData.alertMessage" class="savings-calculator">
Change the class name as well

2022-03-18 15:07 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
> +                    <div class="savings-calculator">
Change the class name as well

2022-03-18 16:24 UTC, VodianytskyiVI commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/loyalty-sale-part.service.ts
> +    providedIn: 'root',
The project's UI doesn't start when I remove this, so I'd leave it as is now

2022-03-18 16:24 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
> +                    grid-area: SavingsCalculator;
This should also change

2022-03-18 16:26 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/loyalty-sale-part.service.ts
> +    providedIn: 'root',
Then remove this service from CoreModule since it's not needed there if it's provided in root

2022-03-18 19:51 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
> +        LoyaltySalePartService
This isn't needed since the service is provided in root

2022-03-21 08:18 UTC, VodianytskyiVI commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
> +        LoyaltySalePartService
Removed, thanks

2022-03-21 08:18 UTC, VodianytskyiVI commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/loyalty-sale-part.service.ts
> +    providedIn: 'root',
Removed, thanks

2022-03-21 13:21 UTC, kdelorey approved these changes

2022-03-21 13:22 UTC, jchirico8 approved these changes

2022-03-21 14:16 UTC, blubaugha approved these changes

2022-03-21 17:27 UTC, merged