Improve model load performance
JumpMind/openpos-framework pull request #2107
Opened 2022-03-17 21:00 UTC by mmichalek

This PR improves model load performance by almost 60%.
[https://github.com/JumpMind/commerce/issues/5915]

2022-03-17 22:59 UTC, jrmihalick reviewed
Hard to digest all of this without some commentary along the way (say in the form of github comments), but that's an impressive performance gain.

2022-03-17 22:59 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelWrapper.java
> +            // which don't include TAGS. BUT
BUT... (then one of your kids fell down the steps). 😆

2022-03-17 22:59 UTC, jrmihalick commented on openpos-util/src/main/java/org/jumpmind/pos/util/model/ITypeCodeRegistry.java
> +    @Getter
I wonder if we shouldn't provide direct access to this cache and just have methods on the registry to get/put values from/to it?

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/AbstractModel.java
> +    private Map<String, Object> additionalFields = new LinkedCaseInsensitiveMap<>();
Al the switching of case around the CaseInsensitiveMaps was showing up as hothpots.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        public void queryForEachRow(Query<Row> query, int maxResults, Map<String, Object> params, Consumer<RowConsumerContext<DbRow>> rowHandler) {
DbRow is similiar to Row, but uses a regular LinkedHashMap, rather than CaseInsensitiveMap.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        return query(query,  new HashMap<String, Object>(), maxResults);
These were not related to the PR directly, but causd NPE if you use these methods.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +                columnsIgnoreCase = row.generateColumnsNamesIgnoreCase();
Generate lowercase column names for the result set only once, instead of for each row.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +            PropertyDescriptor[] propertyDescriptors,
Compute propertyDestriptors only once for each model class, instead of all the time.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
> +    private ModelTagEnhancer modelTagEnhancer;
Refactor tag and augment logic to their own helpers

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
> +    public static final String DEFAULT_COLUMN_SIZE = "32";
Better placement of this

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
> +                        if (regularMeta.getModelClass().equals(superClass)) {
Rename "clazz" to "modelClass" because it seemed more "clazzy" of a name.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DbRow.java
> +public class DbRow {
Again, this is a more performant replacement for Row.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelAugmentEnhancer.java
> +import static org.jumpmind.pos.persist.impl.DatabaseSchema.DEFAULT_COLUMN_SIZE;
This code was factored out of DBSessionFactory

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
> +        propertyDescriptors = PropertyUtils.getPropertyDescriptors(modelClass);
A lot of the heart of the change is here -- figured out the structures of the models up front instead of doing so much work in line.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelMetaData.java
> +    private Field systemDataField;
These are precomputed things about the model that we used to get by reflection on demand.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelTagEnhancer.java
> +package org.jumpmind.pos.persist.impl;
Factored out of DBSessionFactory

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelWrapper.java
> +            // THIS IS SUPPOSED TO MAP COLUMNS to VALUES but then iterates on field values,
Good catch. 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/4398634/158978943-91669546-cb5a-409d-9b8b-5b35ac8ed941.png">

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelWrapper.java
> +        if (!col1.getName().equalsIgnoreCase(col2.getName())) {
Efficiency fix here that also helps saving.  Turns out the Column.equals method is slow because it gets in to all this default value logic.  So short circuit if the name of the column doesn't even match.

2022-03-18 09:51 UTC, mmichalek commented on openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/RaceCarModel.java
> +    @ColumnDef(crossReference="isoCurrencyCode")
Bonus bugfix to allow reference to isoCurrencyCode on superclass.  Previously did not work.

2022-03-18 09:51 UTC, mmichalek commented on openpos-server-core/src/main/java/org/jumpmind/pos/server/config/SecuredAutoConfiguration.java
> +                log.warn("unable to set least perms on {} (non-POSIX-compliant file system)", parent, ex);
Well should be a seperate PR, but really don't want to swallow exceptions

2022-03-18 09:51 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/model/ITypeCode.java
> +        ITypeCodeRegistry.ITypeCodeCacheKey cacheKey = new ITypeCodeRegistry.ITypeCodeCacheKey(typeCodeClass, value);
This cache is because the reflection around loading the TypeCode for each row is a hotspot, so the cache serves the same instance based on Type and value of the code.

2022-03-18 09:51 UTC, mmichalek commented on openpos-util/src/main/java/org/jumpmind/pos/util/model/ITypeCodeRegistry.java
> +            return size( ) > 5000;
Puts a (large) cap on the size of the cache in memory.

2022-03-18 09:53 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelWrapper.java
> +            // which don't include TAGS. BUT
Good catch

2022-03-18 11:08 UTC, mmichalek commented
> Hard to digest all of this without some commentary along the way (say in the form of github comments), but that's an impressive performance gain.

Commentary added
![image](https://user-images.githubusercontent.com/4398634/158992556-846f03d6-96d4-46f2-9550-1ff5e1240701.png)

2022-03-18 13:38 UTC, jrmihalick requested changes

2022-03-18 13:38 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelMetaData.java
> +    public boolean isDefferedLoadField(String propertyName) {
typo, should be `isDeferredLoadField`

2022-03-18 13:38 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelMetaData.java
> +    Set<String> defferedLoadFieldNames = new HashSet<>();
typo, should be `deferredLoadFieldNames`

2022-03-18 13:38 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
> +        Map<String, Object> deferredLoadValues = new LinkedHashMap<>();
Hey, you spelled it right. ;-)

2022-03-18 13:58 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelMetaData.java
> +    public boolean isDefferedLoadField(String propertyName) {
On it

2022-03-18 13:58 UTC, mmichalek commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelMetaData.java
> +    Set<String> defferedLoadFieldNames = new HashSet<>();
On it.

2022-03-18 14:02 UTC, jrmihalick approved these changes

2022-03-18 14:03 UTC, merged