wedge character strip from scan or search
JumpMind/openpos-framework pull request #2109
Opened 2022-03-17 21:15 UTC by JJStarrett

### Issues Fixed
 - Resolves #2108 

### Summary
In the short term, this strips wedge scanner control characters from `scan-or-search` from keyed strings. This is to address sort of a fundamental issue with wedge scanners in that they aren't really scanners in an API sense - more of just automated keyboards. They just simulate keystrokes very quickly. SO we use control characters and a short time out to detect when they're "scanning". However, obviously, it's just keystrokes and there's nothing really to stop them from "scanning" into input fields.

This is compounded by the fact that where this wedge scanner is used - Android mobile TC devices - the keyboard deliberately obscures its keypresses while it's popped. So when the scanner simulates those presses, we just get a whole bunch of `(unidentified)` keys detected. So we can't "see" a control character as it's pressed. We can only see the string afterwards if an input is focused (keyboard is popped).

"Scan" with react keyboard popped: 
![image](https://user-images.githubusercontent.com/39058176/158896080-a3bc5381-b250-4014-b4d6-76a142a04940.png)

"Scan" with react keyboard not popped:
![image](https://user-images.githubusercontent.com/39058176/158896259-fb4ab09d-e692-400d-a831-b0e030d51930.png)

In the long term, we may want to consider how to approach wedge scanners in the future. Since they just simulate keypresses really quickly, is this appropriate to be considered a "scanner" in the Commerce sense?

---

This also adds some additional logging for https://petcoalm.atlassian.net/browse/PDPOS-7785

2022-03-17 22:15 UTC, jrmihalick requested changes
Should the existing change for the Loyalty component be adapted to use your changes here?

2022-03-17 22:15 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner.plugin.ts
> -                charList.push(e.key);
There is another parallel PR with this change, you can remove this.

2022-03-17 22:17 UTC, jrmihalick commented
Also what is the behavior on screens where we ran the default action because the scan is terminated by an Enter key?

2022-03-18 13:17 UTC, JJStarrett commented
> Also what is the behavior on screens where we ran the default action because the scan is terminated by an Enter key?

This should only affect screens with scan-or-search elements (item inquiry, manage users, order pick, transaction search, central price checker, and sometimes sale or return), but do you just mean if we terminate with 'Enter' instead of 'Tab', what happens? I've got two videos in the ticket that should show the two scenarios on item inquiry specifically, but both should be unaffected. We're only filtering the string data after the keystrokes are entered here.

Is there a specific screen you wanted me to validate?

2022-03-18 13:38 UTC, JJStarrett commented
As per standup, going to try new solution of adding scan-part to loyalty customer dialog and see if that works here too. This will remove the auto-focus on the customer dialog prompt and potentially drop support for wedge scanning directly into an input field

2022-03-18 17:28 UTC, JJStarrett commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner.plugin.ts
> -                charList.push(e.key);
Gotcha, Removed

2022-03-18 18:04 UTC, JJStarrett commented
> Should the existing change for the Loyalty component be adapted to use your changes here?

Makes sense, has been adapted

2022-03-18 18:04 UTC, jrmihalick approved these changes

2022-03-18 18:15 UTC, merged