Combine Product Detail thumbnail and main image into one carousel/image
JumpMind/openpos-framework pull request #2563
Opened 2022-10-06 20:10 UTC by starkiller4996

### Issues Fixed
https://github.com/JumpMind/openpos-framework/issues/2562

2022-10-06 21:02 UTC, jrmihalick commented
@starkiller4996 FYI, Petco Zebra res is 360x720

2022-10-06 21:04 UTC, jrmihalick approved these changes
Looks good to me.  Hopefully the user can scroll down on the mobile screen to see the product attributes (e.g., Promotions)?

2022-10-06 22:41 UTC, jchirico8 requested changes

2022-10-06 22:41 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/product/product-detail/product-detail.component.html
> +                        <app-image [imageUrl]="screen.imageUrls[i]"
Isn't screen.imageUrls[i] the same as category?

2022-10-06 22:41 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/carousel/carousel.component.scss
> +    width: 300px;
I don't like a hard width here. This component is used for multiple things that shouldn't have to be fixed later to overwrite the width

2022-10-07 18:10 UTC, jrmihalick approved these changes

2022-10-10 13:36 UTC, jchirico8 commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/carousel/carousel.component.ts
> +    @Input() width = 300;
This is still defaulting to 300 and requiring any other consumer to override it. The 300px width that product detail wants is the exception and should be the only place setting it

2022-10-10 16:19 UTC, jchirico8 approved these changes

2022-10-10 16:28 UTC, merged