added variable to store the last focussed index
JumpMind/openpos-framework pull request #2600
Opened 2022-10-28 18:18 UTC by chandankumarcentric

fixed issue [#8014](https://github.com/JumpMind/commerce/issues/8014)

Commerce PR# https://github.com/JumpMind/commerce/pull/8015

2022-10-28 19:12 UTC, jrmihalick requested changes

2022-10-28 19:12 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action.service.ts
> +    private lastFocusedItemIndex = new BehaviorSubject<number>(-1);
I think you are going to need to find another way to do this. It's out of place to track this in the ActionService.

2022-10-31 12:57 UTC, jrmihalick commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action.service.ts
> +    private lastFocusedItemIndex = new BehaviorSubject<number>(-1);
How is it being handled on other screens without this change?

2022-10-31 19:08 UTC, closed without merging

2022-10-31 19:09 UTC, chandankumarcentric commented
no change needed