feature/improve-logging-during-sql-exception-releases1.0
JumpMind/openpos-framework pull request #849
Opened 2020-09-09 23:58 UTC by mmichalek

2020-09-09 23:59 UTC, mmichalek commented
@gwilmer  - this should also fix the specific error you saw with the remote transaction lookup.

2020-09-10 14:13 UTC, jrmihalick requested changes

2020-09-10 14:13 UTC, jrmihalick commented on openpos-persist/src/main/java/org/jumpmind/pos/persist/model/SearchCriteria.java
> +        if (value instanceof AbstractTypeCode) {
You probably want to check `instanceof ITypeCode` here instead

2020-09-10 14:48 UTC, maxwellpettit approved these changes

2020-09-11 12:49 UTC, merged