Cash Drawer Close Detection
JumpMind/openpos-framework pull request #923
Opened 2020-10-14 22:09 UTC by liambell-le

###Summary
To avoid opening and closing the connection to the printer or storing printer codes, moved waitForDrawerClose to EscpPOSPrinter.

2020-10-14 22:35 UTC, mmichalek requested changes

2020-10-14 22:35 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            throw new PrintException("Failed to get drawer status");
This swallows the real exception

2020-10-14 22:35 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/LogPOSPrinter.java
> +        return 0;
This is where you could simulate a second or two before the drawer closes.

2020-10-14 22:35 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +                    getPeripheralConnection().getOut().write(new byte[]{0x1D, 0x72, 2});
Can this just call isDrawerOpen(String drawerId)

2020-10-14 22:35 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +    public int waitForDrawerClose(long timeout) {
This should also have a String drawerId (In the off chance we ever support 2 drawers connected to the same printer.  But it could happen)

2020-10-15 14:58 UTC, liambell-le commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +    public int waitForDrawerClose(long timeout) {
Added the drawerId. I'm not using it for anything, but it is there to build on.

2020-10-15 14:58 UTC, liambell-le commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            throw new PrintException("Failed to get drawer status");
Removed the throw. Logging caught exception.

2020-10-15 15:01 UTC, liambell-le commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +                    getPeripheralConnection().getOut().write(new byte[]{0x1D, 0x72, 2});
I separated the method into waitForDrawerClose and isDrawerOpen to allow the isDrawerOpen to be used independently.

2020-10-16 16:53 UTC, mmichalek requested changes

2020-10-16 16:53 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            log.warn(e.getMessage());
Swallowed exception

2020-10-16 16:53 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +        int drawerState = 0;
DRAWER_OPEN = 0;
DRAWER_CLOSED = 1;

2020-10-16 16:53 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            getPeripheralConnection().getOut().write(new byte[]{0x1D, 0x72, 2});
Let's move to this String cmd = printer.getCommand(PrinterCommands.CASH_DRAWER_STATE);
            String cmd = printer.getCommand(PrinterCommands.CASH_DRAWER_STATE);

            byte[] bytes = cmd.getBytes();

2020-10-16 16:53 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            log.warn(e.getMessage());
make log exception, 
log.warn("Failed to read drawer status", ex);

2020-10-16 16:53 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/LogPOSPrinter.java
> +    @Override
@SneakyThrows ?

2020-10-21 20:58 UTC, mmichalek requested changes

2020-10-22 17:23 UTC, chenson42 approved these changes

2020-10-23 13:39 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            return getPeripheralConnection().getIn().read() == 1 ? false : true;
Can we replace "1" with DRAWER_CLOSED? #picky

2020-10-23 14:53 UTC, chenson42 commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +            return getPeripheralConnection().getIn().read() == 1 ? false : true;
#done

2020-10-23 16:44 UTC, mmichalek approved these changes

2020-10-23 17:39 UTC, merged