PCOM-191: Update of collapsed Sell Item design and Image service mech…
JumpMind/openpos-framework pull request #928
Opened 2020-10-19 19:12 UTC by avramovicae

…anism

- updated SellItem interface with collapsed labels
- updated workflow of Image service and Image Component mechanism so that
  we now cover use case scenario when Alt image property is misssing or is
  failing.
- updated ItemCard and MobileItem item collapsed looks
- updated SellItem object with collapsedAdditionalLabels property

> ### PR Instructions - *remove this section*
>
> Release notes are generated off of pull requests.  Please follow these instructions so that your pull request is categorized appropriately. 
>  
> Checklist:
> * Update the title of this pull request to be a concise description of the feature or bug fix
> * Add the label *releasenote* if this PR should be included in the release notes
> * Add the label *majorfeature* if this is a major feature.  If the label exists then the full body of the PR will be included in the major features section of the release notes
> * Add the label *databasechange* if there are database changes associated with this feature
> * Add the label *parameterchange* if there are parameter changes associated with this feature
> * If this PR fixes an issue please list it in the Issues Fixed section.  We'll include the issues fixed in the release notes
> * Please fill out the following sections.  If they don't pertain to this pull request then you can remove the section
> * Please remember to make additional PRs for all relevant branches.  We DO NOT automatically merge branches

### Issues Fixed
List the issues that this PR addresses.  Use [github issue number format](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests).

### Summary
A (sometime wordy) summary of the fix goes here.

### Database Changes
List database changes that apply and note their ramification.  If this section applies then add the label _databasechange_ to your pull request.

### Parameter Changes
Have parameters been added, renamed or removed?  If this section applies then add the label _parameterchange_ to your pull request.

### Screenshots
Screenshots go here.

2020-10-19 20:23 UTC, chenson42 commented
@avramovicae Can we get a few screen shots of this in action?

2020-10-20 10:49 UTC, avramovicae commented
@chenson42 Here are screenshots. For the first two I moved style from list of collapsed labels so that there is more visible difference between collapsed and expanded item, since at the moment additional labels by default only contain three properties that are also in collapsed Additional labels. In the last one it shows current state. 
Note: We should check with AE should there be adjustments in default additional labels in SellItem.

<img width="364" alt="Screenshot 2020-10-20 at 12 36 18" src="https://user-images.githubusercontent.com/69313319/96575321-e5a18f00-12d0-11eb-98c8-e40333fad211.png">
<img width="364" alt="Screenshot 2020-10-20 at 12 36 09" src="https://user-images.githubusercontent.com/69313319/96575339-e9351600-12d0-11eb-90c0-2258a0ae312a.png">

<img width="364" alt="Screenshot 2020-10-20 at 12 46 32" src="https://user-images.githubusercontent.com/69313319/96576486-8ba1c900-12d2-11eb-9c91-faa08ecc3e9f.png">

2020-10-20 13:15 UTC, avramovicae commented
@dankaste @chenson42 I have additionally updated image component logic.

2020-10-21 12:32 UTC, dankaste requested changes

2020-10-21 12:32 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/image.service.ts
> +                filter(message => message.configType === 'MediaService'),
This should be getting its configuration from a different config set than 'MediaService'. I was picturing a config set for 'Images'.

2020-10-21 12:32 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/image.service.ts
> +        if(!originalUrl){
I don't think it really makes sense to do this here cause you don't know if the original image has failed to fetch yet. Also this doesn't really fallow the single responsibility principle. This method should only be replacing the tokens in the url and returning back the correct path.

2020-10-21 12:32 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/image/image.component.ts
> +        imgUrl = this.imageService.replaceImageUrl('');
Instead of passing in blank, I think its much more clear if we pass in imageServce.getDefaultImage()

2020-10-21 12:32 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/mobile-item/mobile-item.component.ts
> +    @Input() set _item(item: ISellItem){
I'm not crazy about the '_' prefix on the public property. I believe the best practice is the private has the underscore and the property is camelCase

2020-10-21 12:32 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.ts
> +  @Input() set _item(item: ISellItem){
Swap the underscore prefix with the private variable.

2020-10-21 13:01 UTC, avramovicae commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/image.service.ts
> +                filter(message => message.configType === 'MediaService'),
@dankaste I already created PR with image-not-found in MediaService in yml file in aeo-jumpmind, and this PR is approved and merged by @chenson42 . Should I update this yml file or we can go with this?

2020-10-23 20:36 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/image.service.ts
> +                filter(message => message.configType === 'MediaService'),
Yes please update the yaml file.

2020-10-23 20:44 UTC, dankaste requested changes
Just need to get the ConfigChanged message from the right place

2020-10-27 12:21 UTC, stevencarley approved these changes

2020-10-27 13:21 UTC, stojankz approved these changes

2020-10-28 12:21 UTC, dankaste approved these changes

2020-10-28 14:18 UTC, merged