Bugfix/keypress sources capturing both keyup and keydown master
JumpMind/openpos-framework pull request #949
Opened 2020-11-03 21:30 UTC by stojankz

### Summary
Change fixes an issue where pressing 'Enter' to unlock the lock screen was also using the enter keypress to send the open store dialog action and continue opening the store. This issue resulted from the fact that both keyup and keydown events were being handled for the keypress sources which resulted in the lock screen being handled on keydown and the dialog underneath to capture and use keyup.

Changes made include:
- updating the lock-screen component to use the KeyPressProvider and keypress-source to handle the keypress rather than using a host listener
- updating keypress-source.directive.ts to make sure it's only registering the source to the provider and not also subscribing to keyup and keydown events in the source directive
- updating keypress.provider.ts to add additional optional parameter to subscribe to specify the eventType that the key should subscribe to. If this parameter is not passed in, it subscribes to 'keydown' by default.
- updating keypress.provider.ts rebuildKeyPressObserver function to filter on the event type of the subscriptions and then sort so that it is handling only subscriptions for that key and that eventType(keyup or keydown).
- updating keypress.provider.ts to check the Configuration.keybindsEnabled in the shouldRunGlobalAction function
- updating action-item-key-mapping.directive.ts so that it subscribes to both keyup and keydown to continue to handle the button styling
- cleaned up spacing and formatting

2020-11-03 21:44 UTC, mmichalek approved these changes

2020-11-04 13:01 UTC, dankaste requested changes

2020-11-04 13:25 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
> +        if (isLockScreenEnabled) {
So since this is for the global actions I’m guessing this stops any global actions from occurring when the Lock Screen is enabled. It’s true that the enter button click would stop the propagation but not sure about other keys?

2020-11-04 13:26 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.component.html
> +            <app-rounded-input appKeypressSource [placeholder]="data.passwordHint" [(value)]="password" inputType="password"></app-rounded-input>
Thanks for the input I’ll remove it and test it out to be sure!

2020-11-04 13:41 UTC, dankaste commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
> +        if (isLockScreenEnabled) {
I think the reason we needed this before was because the lockscreen was a dialog and the stop propagation logic was only being hit for screens. So I *think* we should be good now. If you think cleaning that up is out of scope of this PR thats fine. Just drop a comment on that line and we can come back to it later

2020-11-04 16:31 UTC, stojankz commented on openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
> +        if (isLockScreenEnabled) {
I left a comment. I tried to change and test it out but I couldn't seem to get a global action to trigger. I'm not sure why or if I was doing something weird so I didn't feel comfortable making the change without being able to test it.

2020-11-04 16:45 UTC, chenson42 approved these changes

2020-11-04 17:28 UTC, blubaugha approved these changes

2020-11-05 14:46 UTC, dankaste approved these changes

2020-11-05 15:11 UTC, merged