Fix signature line cutoff by printer
JumpMind/openpos-framework pull request #967
Opened 2020-11-12 15:54 UTC by JJStarrett

### Issues Fixed
 - [3112](https://petcoalm.atlassian.net/browse/PDPOS-3112) 

### Summary
Previously, the Epson printer seems to have been cutting off the bottom of cash management receipts as to obscure the signature line. This should no longer happen.

### Screenshots
![image_from_ios](https://user-images.githubusercontent.com/39058176/98963053-3de53e80-24d5-11eb-82a7-062aaf3f147c.jpg)

2020-11-12 16:10 UTC, liambell-le approved these changes

2020-11-13 19:15 UTC, chenson42 approved these changes

2020-11-13 19:16 UTC, chenson42 commented
don't forget to make PR for master as well

2020-11-13 19:47 UTC, mmichalek requested changes
I don't think we need this. NCR does not use this.

2020-12-03 13:13 UTC, chenson42 commented
@JJStarrett Is this still a valid PR?  Should it be closed?

2020-12-09 23:57 UTC, closed without merging