Feature/support toshiba tcx suremark printer
JumpMind/openpos-framework pull request #995
Opened 2020-11-25 19:05 UTC by mmichalek

### Summary
Support toshiba tcx suremark printer

2020-11-27 13:08 UTC, chenson42 approved these changes

2020-11-30 13:18 UTC, jrmihalick requested changes

2020-11-30 13:18 UTC, jrmihalick commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +    // certain configurations have to be configured for "unsoliciated status" to work properly, which means
unsoliciated -> unsolicited?

2020-11-30 14:22 UTC, jrmihalick approved these changes

2020-11-30 14:52 UTC, mmichalek commented on openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
> +    // certain configurations have to be configured for "unsoliciated status" to work properly, which means
Thanks for the unsoliciated feedback sir.

2020-11-30 16:27 UTC, merged